papis/commands/export.py
Fix bug when using the --out flag in export --bibtex to correctly append the output to a file.
=> fix bug in --out flag of export

examples/scripts/papis-scihub
Today sci-hub io, bz, biz, ac and cc seems down, while tw is working
=> papis-scihub: Add new scihub domain (.tw)

papis/config.py, papis/crossref.py
This PR brings the implementation of the `ref-format` flag. This allows the user to set their preferred format to reference when using in conjunction with .bib files. Or for remembering a article by an easy to remember combination of information (e.g. AuthorYear) rather than the doi.
The default behaviour is for the ref to be set to the doi.
Closes #16
=> New config flag: ref-format

papis/crossref.py
Hello!
The DOI foundation recommends a [new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8).
Cheers :-)
=> link DOIs to preferred resolver

README.md, ROADMAP.md
papis is now on nixpkgs! It's on the unstable channel (meaning that it's available to those that are on the bleeding edge, while I think it will become available on stable release that usually happens on March). 
I also removed a couple of whitespaces and fixed a wrong capital word (added the reference to the grammar, I'm not english but I'm quite sure it's right)
=> NixOS repository package

papis/crossref.py
ref tags with whitespace cause errors if they are used for
bibtex. Now, ref tags are run through command `collapse_whitespace()`
to remove any whitespace put in by the user (in ~/config/papis) or
from anything pulled from scrapers.
Fixes #67
=> Removal of whitespace from ref tags

examples/scripts/papis-zotero
papis-zotero will now add a bib file to a specified library using
the `--pick-lib` or `-l my_lib` flags.
Closes #75
=> papis-zotero now honours library options

examples/scripts/papis-hubation, papis/config.py, papis/document.py
(1) `papis hubation` now searches the users library to see if
documents are already present.
(2) Some users are unable to use the scihub script. These
modifications to the hubation script allow users to tell hubation what
to do after a citation is picked, defined in `config` as
'hubation'. So far, `open`, `browse`, and `export` have been tested
and are working. With changes described in (1), `open` will try to
open the document file if the document is already present in the users
library. If not, a browser is opened using the scraped url.
(3) Added has_citations property to papis.document to check if the
document entry has citations associated with it. This can be set in
any 'header' option and returns 'citation-string' if True.
(4) Added 'citation-string' config option. If …
=> Improved search citations (hubation)

papis/config.py, papis/document.py
`bibtex-journal-key` lets the user define the key that `papis
export --bibtex` uses when assigning the `journal` bibtex
entry. This allows the user to define `full_journal_title` or
`abbrev_journal_title` depending on the publishers requirements.
Closes #73
=> Added `bibtex-journal-key` option

examples/scripts/papis-hubation
Now by adding an optional reference number from the article as a
command line argument, papis hubation will stop searching when it gets
to that reference and return the result.
Closes #84
Also some other minor bug fixes
=> [hubation] Added an optional reference number argument

examples/scripts/papis-zotero-sql
- When importing from Zotero SQL, the items' 'collections' should also be imported
- Collection in Zotero corresponds to `project` metadata for papis
- Does not respect collection hierarchy from Zotero (projects are all at the same level in papis)
- Treats collections with the same name as the same collection
=> Import zotero collections to project

examples/scripts/papis-zotero-sql
- zotero-sql was not working for me because my SQL database had a slightly different structure
- After inspecting my database I made some changes to some of the table names in the script, but then the author list was out of order
- Then, updated the ORDER BY criteria for creators
=> Fixed zotero-sql to work for 5.0.55.1

papis/docmatcher.py
`DocMatcher` needs to be able to handle jinja2 templating when a query of the form `key=value` is given to a papis command.
=> Fixed DocMatchers query string for jinja2

papis/bibtex.py, papis/config.py, papis/document.py
I was having issues where I had papis field names that didn't match a corresponding bibtex key. So I made two conversion dictionaries (one for types, one for fields). Also, since I'm using XeLaTeX most of the time I added a configuration variable to allow unicode in the bibtex output.
=> Slightly more robust bibtex handling

examples/scripts/papis-zotero-sql
This looks for "Citation Key" in the "extra" key of zotero and generates a ref from it.
The ref is correctly found when I look at the output of the conversion script yet in the info.yaml, it's always zotero's key that appears.
I don't know if it's overwritten or not ?
I would love some tips in order to get my .tex compile without  touching every ref :)
=> zotero-sql: import mendeley keys when present

scripts/shell_completion/Makefile, scripts/shell_completion/click/papis.zsh
The idea is to have compdef automatically pick it up without having to generate it at runtime (slow) for every shell.
This doesn't work though :/
=> [RDY] zsh completion automatic pickup attempt

CHANGELOG.md, doc/source/default-settings.rst, papis/commands/export.py, papis/config.py, setup.py
Just a Proof of concept to show how it would work, the plugin can be a class instance but here a function was enough.
I added a --format parameter to the export command since the exporters are now dynamically loaded.
The current syntax is kinda strange since you don't really know what to expect from `export --json --yaml --text`, better to enforce a single export format.
`papis export --format=bibtex --all`.
Whit this design, if you install a package that registers an entry_point for 'papis.exporter', it would appear in papis `export --format` options.
=> [RDY] poc for export plugins

setup.py
This is required [here](https://github.com/papis/papis/blob/v0.9/papis/downloaders/base.py#L210) and not installed on the CI, so it caused a few failures for the downloader tests.
I didn't add a minimum version because I'm not sure what a good one would be.
=> Add lxml dependency

doc/source/git.rst
Update documentation to use the correct git flag: `-a` doesn't exist. `-A` does (and was probably meant), but its long version `--all` is IMHO more understandable.
=> Fix git flags in documentation

papis/commands/addto.py
Sometimes when adding a document with no files to a library and then
later trying to use `addto` there would be an error because the document
(i.e. the YAML file) had no `files: []` entry. This commit ensures that
in the event that `files` key is not present that the key is added and
instantiated with an empty list.
=> Ensure `files` key is present in document

papis/commands/list.py
Hi,
This changes the behaviour of the `papis list --libraries` command to print the name of the library in addition to its location.
I found it useful because I couldn't remember the exact names of some of the libraries I have.  It was helpful to be able to print them out with a single command.
Is this OK to go in?
Jackson
=> Print the library name when `papis list --libraries` is called

README.rst
makes it easier to get what `papers` is about.
=> doc: mention similar software

papis/commands/rm.py, tests/__init__.py, tests/commands/test_rm.py
Hi,
I noticed many of the commands have an --all option to repeat the command for all matches.  This adds an identical option to the rm command.
There are no additional test failures.
Any thoughts?
Jackson
=> Add rm --all option

doc/source/default-settings.rst, papis/config.py, papis/docmatcher.py, papis/utils.py, setup.py, tests/test_utils.py
It makes little sense to have a separate path specifically for jinja2.
Same behavior should be achievable via plugins.
=> jinja2: remove support

.travis.yml, appveyor.yml, setup.py
It's probably safe to drop support for Python <= 3.4 as they are neither maintained nor receiving security fixes.  (Unless there's another reason for keeping this support)
=> Update supported Python version to 3.5, 3.6, 3.7 & 3.8

.github/ISSUE_TEMPLATE.md
I've seen a few issues that don't explicit the version in use, which make diagnostic harder.
Eventually we could add a template for feature vs bug as one can see when creating an issue on  https://github.com/NixOS/nixpkgs/issues.
=> github: add a template for new issues

papis/commands/list.py
Hi,
Previously,
`papis list "*" --sort ...` did not actually sort anything, becuase the sorting function was applied after the picker.
This patch moves the application of the sorting function to before the picker to fix this bug.
Good to go in?
Jackson
=> Move the sort call in `papis list` so it is applied before the picker

papis/commands/add.py, papis/document.py, papis/strings.py
Hi,
(Replaces #256 )
This patch series introduces timestamps when documents are added to papis, using a `time-added` field in the document metadata.
The big benefit of these timestamps is that they allow document sorting by recency of addition.
The patches are as follows:
4bdb4b:  In add.py, put a timestamp in the document metadata.
9baf197 and 031b46c modify the sorting algorithm in a way that makes sense regardless, but makes the following changes easier.
a660ce7: Adds a special condition to the sorting algorithm to check if each document has a field called `time-added`.  If it does, that document is sorted by date instead.
Notes: There are a couple things I have left out here that could go in.  First, `time-added` is a human-readable date.  An alternative that would not require change …
=> Document Timestamps

papis/bibtex.py
Performed bugfix on current code base. Original PR message:
> Moved the translation of keys to proper bibtex keys to its own loop.
>
> Avoids ambiguity with the loop iterator in the following loop for bibKey in sorted(document.keys())
> Fixes #134
=> Modernized PR #177

papis/pubmed.py, tests/test_pubmed.py
The [current url](http://pubmed.macropus.org) for retrieving pubmed data seems to be dead. This PR switches the importer to use https://api.ncbi.nlm.nih.gov/lit/ctxp instead. This seems to be offered by the NCBI so hopefully it works well enough. 
There's also [TexMed](https://www.bioinformatics.org/texmed/), which seems to offer results directly in bibtex. Would you prefer querying that?
=> Update PubMed Importer

papis/database/cache.py
When a string with regex-relevant data is passed into this function, these characters should be escaped. Otherwise, invalid regexes could appear and lead to strange errors.
I think the double `.*` at the beginning is also not ideal, but I am not entirely sure if my edit is the most sensible choice.
The problem which occured in my use case was that I had some bibtex which I wanted to import and that included ISBN numbers which where placed in curly braces. In combination with this function, this lead to regexes like `.*{123456}` which are not valid.
=> escape strings in get_regex_from_search

config.py, papis/bibtex.py, papis/commands/add.py, papis/commands/browse.py, papis/commands/explore.py, papis/commands/list.py, papis/commands/open.py, papis/commands/update.py, papis/database/cache.py, papis/document.py, papis/format.py, papis/pick.py, setup.py
* add `format.py` file that contains the default `PythonFormater` and `Jinja2Formater`
* add entry points in `setup.py` as
```
'papis.format': [
'python=papis.format:PythonFormater',
'jinja2=papis.format:Jinja2Formater',
],
```
* add config value `formater`, choices are `python` (default) or `jinja2`.
=> Format plugin

papis/pick.py
Tested and it removes the trailing `\n` and the entries appear as intended in the picker. Thanks to @alejandrogallo for identifying the appropriate line of code to look at.
=> Fix for #291

doc/source/default-settings.rst, papis/bibtex.py, tests/test_bibtex.py
Hey,
first of all: thanks for writing papis, its a very useful tool for me. 
While the cleanup when generating a ``ref`` introduced in 216616839754771602ec29f4f2a10d111ea409a7 is very useful, I'd like to place a dot in my refs (e.g. to divide author and year). Therefore, I would like to suggest the possibility to escape characters in `ref-format` -- here implemented for ``.`` and ``_``.
Specifying ``ref-format = {doc[author]:.10}\.{doc[year]}`` would result in refs like ``MeshKiAngN.2020``.
=> Allow to escape dots and underscores with a backslash in ref-format

setup.py
Allows plugins that use `papis` to also be type checked. From https://www.python.org/dev/peps/pep-0561/#packaging-type-information.
=> Add a py.typed file

papis/bibtex.py, papis/document.py, papis/isbn.py, tests/resources/isbn/test_isbn_1.json, tests/resources/isbn/test_isbn_1_out.json, tests/test_isbn.py
Extracts a papis friendly `author_list` from isbnlib's list of authors.
The added test data has an example of before/after.
=> Improve isbn_to_papis conversion

papis/database/cache.py, papis/tui/widgets/list.py, papis/utils.py
Hi,
Trying to use papis on platforms without multiprocessing (android in
my case) currently fails.  With this PR we check if multiprocessing is
supported before trying to use it.
Without this patch, running for example
```sh
wget http://www.gnu.org/s/libc/manual/pdf/libc.pdf
papis add libc.pdf --set author "Sandra Loosemore" --set title "GNU C reference manual" --set year 2018 --set tags programming --confirm
```
gives
```
INFO:importer:pdf2doi:Trying to parse doi from file libc.pdf
ERROR:yaml:Yaml syntax error: 
'utf-8' codec can't decode byte 0xd0 in position 10: invalid continuation byte
INFO:utils:matcher:libc.pdf matches fallback
ERROR:utils:matcher:Invalid URL 'libc.pdf': No schema supplied. Perhaps you meant http://libc.pdf?
INFO:cli:add:These importers where automatically matched, …
```
=> Add support for platforms without multiprocessing (like android)

papis/database/cache.py, papis/tui/widgets/list.py, papis/utils.py
Before trying to open a document with `papis open` and then starting to type would freeze the tui completely.
=> Fix deadlock when filtering with the list widget

papis/commands/edit.py, papis/tui/__init__.py, papis/tui/app.py
This commit adds possibility to edit notes from the default picker (see #316). 
Currently, I set the default keybinding to `c-m` but that's mostly just to have anything (both `c-n` and `c-e` which would seem like the obvious choices are already in use).
With this commit, I want to get some feedback on how to best implement the feature. What I've done is to separate out, in `edit.py` from the function`cli` everything that relates to editing notes and created a new function (`edit_notes`) with it. This is so i can call that function in `app.py`. I'm not sure this is the best way of doing this; it breaks a bit with how the other command files are structured. I've also commented out a bunch of logging stuff as maybe we want to call these only when the function is called as a cli command?
What …
=> [WiP] Add open note functionality to picker (issue 316)

README.rst
This PR moves a backtick around to fix the link to papis zotero and formats the the export format list.
=> Fix link to papis zotero, minor typesetting.

.github/workflows/main.yml, papis/commands/browse.py, papis/commands/merge.py, papis/config.py
And fix minor issues that the coverage check complained about in browse.py and merge.py. Also add a missing space to the message that is printed if library does not exist.
=> Add python3.10 to versions to run tests on

papis/commands/default.py
This fixed a breakage from #345 (sorry!). There are a few places that do
```
logger.error(e)
```
where `e` is an exception, that made this give a scarier error message.
=> Check msg is a string in ColoramaFormatter

papis/commands/default.py
Another fix after #345 :(. I'm starting to think that `ColoramaFormatter` thing is more trouble than it's worth!
The issue here was that logger in the `MultiCommand` class gets created and stored before the `default` command gets a chance to execute and set up all the logging infrastructure. This means that `ColoramaFormatter` does not get set and called, so the logged message contained the `colorama` codes.
=> Fix logger message in MultiCommand class

doc/source/default-settings.rst
The ranger link in the documentation of the config section pointed to an outdated website.
=> update ranger link

README.rst
Unless I am missing something, this example is missing the `--format` part of the export.
=> fix export example in the readme

papis/config.py
Fix #249.
Can you think of any circumstances where this approach would fail?
=> Use configured default-library instead of default value

doc/source/default-settings.rst, papis/commands/edit.py, papis/config.py
Added the ability to create a template for notes. The template is then formatted with the configured formater. This makes it easy to quickly edit new notes in a standardized way, which can be especially useful when writing notes in markdown, latex, ect. To use a template-file, one needs to specify the path to the template-file in the 'notes-template'-variable in the configuration. Templates are generated when editing notes of a reference for the first time (`papis edit -n`).
The following gives an example of a somewhat useful template-file for markdown, using the jinja2-formater:
```md
**Authors**: {{ doc.get( "author", "" ) }}
---
**Tags**:
**Files**:
{% for l in doc.get('files', []) %}
- [{{l}}]({{l}})
{%- endfor %}
---
```
which would look like this:
```md
**Authors**: Author1, Author2 …
```
=> added template functionality for new notes

doc/source/default-settings.rst, papis/commands/edit.py
I thought it would be more consistent to use the formater on the ``notes-name`` as well. This could for example be useful if one would like to name the notes similar to the title of the reference. Static notes-names can of course still be used (at least with the default ``python``-formater or ``jinja``-formater).
Also, I added a little more documentation for ``notes-name`` and ``notes-template``.
Finally, I forgot to import ``papis.format`` and fixed it herewith. However, I must admit that I don't understand why calling ``papis.format.format()`` works in the first place, without importing ``papis.format``. Is ``papis.format`` imported globally?
=> Template notes

papis/commands/edit.py, papis/commands/rm.py
Similar to `papis rm --file`, I added the option `-n`/`--notes` to delete the notes-file. Thereby, the info file of the document is updated accordingly. Deleting the notes-file works also with the options `--all` and `--force`. Furthermore, it's also possible to use both options `--file` and `--notes` simultaneously.
Besides that, I discovered and fixed a bug that occurred, when creating new notes for a document. Before the fix, the database would not update the document after adding a new notes-file. Therefore, one had to run `papis --cc` after creating new notes. I didn't find any open issue about that.
=> added option to delete notes-file of a document

papis/commands/add.py
Addresses #386 
As discussed, the importer is only used to download files if no local file is passed or the new `--force-download` flag is set.
It seems that the docs are automatically generated so I did not add anything there. Let me know if there is something missing.
=> Add `force_download` flag to `add` command

config.py, doc/source/default-settings.rst, papis/commands/add.py, papis/config.py
* Added a ini config option named `add-subfolder` to set a default for `--subfolder` on `papis add`
* Made the config option `add-folder-name` s.t., it can create
subfolders in the library based on document properties, e.g., grouping all papers from a year into subfolder with `{doc[year]}/{doc[title]}`.
* I switched to using `pathlib` from the python standard library for handling the paths instead of using the `os.path` functions.
=> More flexibility to put newly added entries in configurable subfolders.

papis/commands/add.py, papis/pick.py
This pull-request adds the option `-p`/`--pick-subfolder` to the `papis add` command. When using this flag, then the configured picker is called to choose a parent-subfolder. This option can be used together with the `-d`/`--subfolder` flag, to create a new subfolder inside the picked subfolder.
The list of subfolders to pick from is defined by iterating over all documents in the library, setting the parent folder of each document as a subfolder. This leads to the problem of not finding empty subfolders (folders that do not containing any documents) in the library, though this might be also the expected/logical behavior?
=> adds -p/--pick-subfolder option to `papis add`

papis/config.py
Should this get a test somewhere? It works locally.
Fixes #397.
=> Use default default-library if not in user config

papis/commands/add.py
It seems like the `folder_name is None` case was broken when `out_folder_path` was introduced.
This should hopefully fix that, but I haven't tested it :grimacing:
=> add: Remove unused out_folder_name variable

papis/commands/edit.py, papis/commands/update.py
Currently, when using `papis update --set notes [notes-name]`, the notes-name gets formatted (enabling dynamic notes filenames), but it does not get cleaned. This is inconsistent with the behaviour of the `papis edit` command (as implemented [here](https://github.com/papis/papis/commit/de95c01606c32c420f532e1413d0f1d7a703cf12)). This PR makes the behaviour of the edit and update commands function the same when adding notes.
An additional advantage is that it allows me to implement my papis neovim plugin more easily (see the discussion [here](https://github.com/papis/papis/discussions/388#discussioncomment-3643124)).
My python and git knowledge is still a bit sketchy, so let me know if there's anything to improve.
=> Clean notes filename when using `update --set`

README.rst
I've recently published the first iteration of a [neovim plugin for papis](https://github.com/jghauser/papis.nvim). While definitely still work-in-progress, it's probably quite a bit more advanced than the existing vim plugin and should be stable enough for most. I'm using it myself and am committed to further updating and improving it.
=> docs: add papis.nvim plugin

setup.py
The `LICENSE.txt` was removed the other day.
=> Fix LICENSE file rename in setup.py

.readthedocs.yml
The documentation for the new config format is at
https://docs.readthedocs.io/en/stable/config-file/v2.html#python-install
As far as I can tell, this is correct, but I obviously can't test it :(
I haven't managed to get these configs right from the first try, so it's likely it'll need some fiddling after merging..
=> Update readthedocs config to version 2

papis/commands/serve.py, tools/ci-install.sh
Turns out `flake8-quotes` is incompatible with `flake8` v6, so this just pins it to older versions for now.
I'll go ahead and merge once the CI passes again.
=> Pin flake8<6 until flake8-quotes is fixed

tests/__init__.py, tests/commands/test_add.py, tests/commands/test_explore.py, tests/commands/test_export.py, tests/test_config.py, tests/test_document.py, tests/test_utils.py
This fixes two issues:
* do not use `tempfile.mktemp` (e.g. https://github.com/papis/papis/security/code-scanning/329) and use `tempfile.TemporaryFile` and friends in a context manager instead. This should also have the benefit of cleaning up the tests files after the test is run.
* use `pytest.monkeypatch` to change `os.environ` (see https://docs.pytest.org/en/7.1.x/how-to/monkeypatch.html)
The changes are just in the tests, so I'll merge when this passes :rocket:
=> CodeQL fixes

papis/document.py, tests/test_document.py
Managed to mess up the `join` in https://github.com/papis/papis/pull/419/files#diff-682cf814342bcf093b2680414653beea5744a9aab988d8bdabbe528a6b177391. This updates `papis.document.dump` a bit:
* adds the missing new lines (fixing a bug!)
* aligns the keys / values when dumping so that it's a bit easier to follow
* adds a test so that the formatting doesn't get messed up by mistake in the future!
=> Fix missing newline in papis.document.dump

papis/commands/default.py
By default, i.e. for "auto", this should make papis honor `NO_COLOR`.
https://no-color.org/
=> Add support for NO_COLOR when setting up colorama

doc/source/commands/add.rst, doc/source/conf.py, papis/commands/add.py, papis/commands/addto.py, papis/commands/bibtex.py, papis/commands/browse.py, papis/commands/config.py, papis/commands/default.py, papis/commands/edit.py, papis/commands/exec.py, papis/commands/explore.py, papis/commands/export.py, papis/commands/list.py, papis/commands/merge.py, papis/commands/mv.py, papis/commands/open.py, papis/commands/rename.py, papis/commands/rm.py, papis/commands/run.py, papis/commands/update.py
This is meant to help address a note from https://github.com/papis/papis/discussions/413#discussion-4496598 (in the Commands section).
Before, the docs looked like https://papis.readthedocs.io/en/latest/commands.html#cli. This removes a level in the sections and looks like this (i.e. remove the extra `papis add` heading)
@jghauser Can you take a look and see if this is more like what you had in mind? The code is quite hacky, but it seems to get the job done..
=> Fix click command heading

papis/bibtex.py, tests/test_bibtex.py
Improves the handling by
* skipping the document if no `bibtex_type` can be determined
* skipping the document if no `ref` can be determined
* adding some error messages to see which documents are causing problems
@jghauser Does this help with #407? It should at least skip documents with no `ref` like the one in your example. I tried modifying some files in my library, but don't have anything substantial to test with.
=> Better error handling in to_bibtex

papis/downloaders/base.py, papis/downloaders/springer.py, tests/downloaders/resources/APS_PhysRevLett.122.145901_Out.json, tests/downloaders/resources/APS_PhysRevX.12.041027_Out.json, tests/downloaders/resources/APS_RevModPhys.94.045004_Out.json, tests/downloaders/resources/SpringerLink_BF02727953_Out.json, tests/downloaders/resources/SpringerLink_s10924_010_0192_1_Out.json
To be clearer, this fixes parsing of names like `"Smith, John"`, where previously it would split on the whitespace and take the first element as the given name and the second one as the family name. That name format showed up in the `Springer` downloader.
This PR switches to using `papis.document.split_authors_name`, which uses `bibtexparser` under the hood to do a bunch of fancier heuristics.
=> parse_meta_authors: improve author parsing

papis/bibtex.py, tests/test_bibtex.py
The manual can be found at https://ctan.org/pkg/biblatex?lang=en. Is there some more authoritative source?
This PR updates the existing mappings and list of types and keys from the latest version of the document. Hopefully without any typos..
=> Update bibtex_types and bibtex_keys from biblatex manual

papis/bibtex.py, tests/test_bibtex.py, tests/test_document.py
Some updates while doing #412. The main changes are:
* only do one sweep through the document keys (i.e. do the `bibtex_key_converter` directly)
* construct a `List[str]` with the bibtex lines and join at the end. Using `str += extra` is known to be quadratic.
For a few simple benchmarks (using hyperfine) trying to export ~20 and ~200 papers (library has about ~1500). Before it was
```
Benchmark 1: papis -l papers export -f bibtex -a greengard
Time (mean ± σ):     420.5 ms ±   6.8 ms    [User: 440.8 ms, System: 194.0 ms]
Range (min … max):   407.9 ms … 432.8 ms    10 runs
Benchmark 2: papis -l papers export -f bibtex -a optimization
Time (mean ± σ):     525.7 ms ±   4.9 ms    [User: 562.8 ms, System: 184.5 ms]
Range (min … max):   518.9 ms … 536.8 ms    10 runs
```
and now it is
``` …
```
=> Improve to_bibtex performance

CHANGELOG.md, doc/source/index.rst, doc/source/papis_id.rst, papis/commands/add.py, papis/commands/serve.py, papis/database/base.py, papis/database/cache.py, papis/database/whoosh.py, papis/id.py, papis/web/paths.py, papis/web/timeline.py
This is already working, I will probably update the webapplication to use this
as a test, and implement a couple of tests.
I think the changes were quite minimal and they are not noticeable in the runtime.
Also the unique id is the same for both databases (namely `papis_id`) and
the only part of papis that knows about it (`papis.id` module) (and probably will know at all in teh future)
is database, so that @jghauser in principle can now use
`papis open papis_id:lalalaalalaala`
in both databases interchangeably.
In python, there is the handy
```
db.find_by_id("lalalaalalala")
```
that throws if two documents match this id.
=> Initial working implementation of papis_id

papis/commands/add.py, papis/utils.py
Should be a fix for #448.
Tests are not performed, as adding a trailing slash to `folder` when [creating the test library](https://github.com/papis/papis/blob/a81e575006b630a3558063cfc6878338ce3bf683/tests/__init__.py#L118) causes the tests to get stuck in the while loop without the fix, which I don't think is helpful.
=> Fix being stuck in `while` loop when adding an entry

.github/workflows/main.yml, Makefile
This adds 
* a `doc` target that should make the docs in HTML format.
* a `test` target that just runs pytest.
* a `ci-install` and `ci-test` target to install and run the tests like on the ci.
@jghauser hopefully these are helpful!
=> Add some more helpful targets to Makefile

README.rst
LGTM went EOL on December 15th, so this removes the badge.
@alejandrogallo The `coveralls` badge also points to something that still uses the TravisCI and hasn't been updated in a long time. Can you update that or should I remove it as well?
=> Remove LGTM badge

papis/pick.py
Not quite sure why no other test or linter picks this up, so it's a bit annoying..
EDIT: `pylint` picks it up, but that's a bit noisy, so I don't know if it's worth enabling on the CI.
=> Fix a circular import cli->pick->api->pick

doc/source/default-settings.rst, papis/bibtex.py, papis/defaults.py
I needed a setting to not export the abstract of my big library, so that other programs
have a better time parsing it.
I think this is a useful addition to the bibtex settings, what do you people think?
=> Add working implementation of bibtex-ignore-keys

doc/source/default-settings.rst, papis/commands/config.py, papis/config.py, tests/commands/test_config.py, tests/downloaders/__init__.py, tests/test_config.py
Was trying to figure out what configs were used in my venv and fell down a little rabbit hole!
This make some updates to the ``config`` command:
* Improve the docs a bit.
* Do not show scary tracebacks on errors, but some hopefully helpful error messages.
* Allow more positional arguments to query multiple settings at once.
* Added `--default` to show all the defaults papis knows about for a given section (could be helpful to explore the settings without going into the code)
* Added a `--json` flag to print multiple options in the json format instead of the default INI-ish format.
@jghauser if you have the time to take a look at the documentation parts (phrasing and such), it would be greatly appreciated, as usual!
=> Improvements to commands.config

papis/commands/default.py
Before it was writing out an ASCII file with some statistics sorted by time. Unfortunately that couldn't be loaded into e.g. `gprof2dot` to visualize it a bit better.
This dumps the raw profile data instead so that other visualization apps can be used.
cc @j-c-w It's been a while, but you added this, so any feedback is very welcome!
=> commands.default: Dump raw profile data

papis/logging.py
In #465, I changed the logging setup to only apply to the `"papis"` logger and its children, which are determined from the naming scheme `papis.submodule.subsubmodule`. This doesn't work great with scripts or other packages that try to use `papis.logging` and be consistent with the rest of `papis`.
To fix that, we could
* use `logging.basicConfig` like before to set the style for all loggers in the process.
* use `getChild` like in this PR.
I prefer this because it keeps all the loggers under the `papis` umbrella. However, removing the `basicConfig` probably messed up setups that relied on `papis` to set up the formatting, so I'm definitely open to reverting to that.
=> Use getChild in get_logger to parent scripts

HACKING.md, Makefile
Typing `make help` now prints
```
Specify a command. The choices are:
help               Show this help
shell_completion   Generate shell completion scripts
update-authors     Generate AUTHORS file from git commits
tags               Generate ctags for main codebase
doc                Generate the documentation in doc/
test               Run pytest test and doctests
ci-install         Install dependencies like on the CI
ci-test            Run tests like on the CI
```
which seems useful enough. This updates the `HACKING.md` to mention using the Makefile and some other things.
=> Add some help messages to the Makefile

papis/crossref.py, tests/resources/crossref/test_conference_out.json, tests/test_crossref.py
The extractor would previously just pick the second link in the list, even if there wasn't one. This updates it to pick the link marked as `"similarity-checking"` (seems like that's the better one). 
There's some documentation on the link format [here](https://github.com/CrossRef/rest-api-doc/blob/master/api_format.md#resource-link).
Fixes #379.
=> Fix link extraction in crossref

papis/commands/add.py
This just moves the `ref` construction a bit higher up in `commands.add.run` so that the folder name construction can potentially use it as a key.
=> commands.add: construct ref before folder names

setup.cfg
This ensures that only the flake8 checks defined in `setup.py` are checked even when there are others installed on the system (I have flake8-isort and this was very annoying).
=> flake8: select chosen plugins only

papis/bibtex.py, papis/downloaders/__init__.py, papis/pubmed.py, setup.cfg
This goes through the downloaders and importers and removes any automatic `ref` conversions, which would interfere with the automatic ref construction in `commands.add`.
Fixes #376.
=> Do not generate refs in importers and downloaders

papis/arxiv.py, papis/base.py, papis/config.py, papis/crossref.py, papis/dissemin.py, papis/downloaders/__init__.py, papis/downloaders/citeseerx.py, papis/downloaders/ieee.py, papis/downloaders/thesesfr.py, papis/isbnplus.py, papis/pubmed.py, papis/utils.py
This adds a `papis.utils.get_session` that returns a `requests.Session` object to be used everywhere with the user-agent and proxies set by the user. This also replaced all the `urllib` usage.
Benefits: `requests` API is nicer; headers and proxies set consistently; some savings on multiple requests?
Downsides: ?
=> Use singleton requests.Session object

examples/scripts/papis-abbrev, examples/scripts/papis-check, examples/scripts/papis-ga, examples/scripts/papis-mail, examples/scripts/papis-tags, papis/api.py, setup.cfg, tests/commands/test_add.py, tests/commands/test_addto.py, tests/commands/test_edit.py, tests/commands/test_export.py, tests/commands/test_list.py, tests/commands/test_mv.py, tests/commands/test_open.py, tests/commands/test_rename.py, tests/commands/test_rm.py, tests/commands/test_run.py, tests/commands/test_update.py, tools/ci-run-tests.sh
This cleans up the example scripts a bit to get them more in line with recent changes.
* Add flake8 checks and fix errors
* Rename `query_option` to `query_argument`
* Use `papis.logging`
* Add typing annotations and some docs to each script
* Use `argparse` in `papis-abbrev` and `papis-ga` instead of manually parsing `sys.argv`.
* A bunch of misc changes to the style, e.g. `key in doc` instead of `key in doc.keys()`.
I've tested the scripts and they seem to be working as expected for some simple examples.
cc @michaelplews: This makes some non-trivial modifications to the `papis-tags` script, so just a heads-up in case you're still using it (as the original author from `git blame`)! If you are still using it, feedback is very welcome!
=> Update example scripts

papis/commands/doctor.py, tests/test_doctor.py
Went a bit over the `papis doctor` code to add tests and updated some more things. Some of the more noticeable changes are:
* `files`: use a list comprehension; use `papis.api.save_doc`.
* `keys-exist`: use a list comprehension.
* `refs`: separate creating and fixing refs (to have better log messages); make the regex global (created once for all docs)
* `duplicated-keys`: use a set instead of a list (faster `x in set`); better handling of `None` (i.e. keys not existing on a document)
* `bibtex-type`: separated type not defined and type unknown (for better messages).
* `key-type-check`: renamed to `key-type`; made all the `eval` hopefully a bit safer.
* `html-codes`: updated regexp from W3Schools; added log message 
* added a `--list-checks` command line option that also prints out the …
=> Doctor: tests, docs and formatting fixes

examples/scripts/papis-abbrev, examples/scripts/papis-check, examples/scripts/papis-ga, examples/scripts/papis-tags, papis/commands/default.py, papis/commands/external.py, papis/logging.py
This improves the logging setup for scripts loaded through `papis.commands.external`, which before didn't pick up the settings passed to the command line.
This is done by:
* exporting some environment variables in `papis.commands.external`: `PAPIS_LOG_LEVEL`, `PAPIS_LOG_COLOR`, `PAPIS_LOG_FILE` and `PAPIS_DEBUG`.
* Having `papis.logging.setup()` take default values from the environ if they exist.
* To make everything consistent, `papis.commands.default` also takes the defaults from the environment if they exist.
Now a script just needs to add an empty `papis.logging.setup()` and it should just work™ :grin:
=> Improve external script logging

papis/document.py, papis/format.py, papis/utils.py, tests/test_format.py
This uses `codecs.decode` to unescape newlines (and others) from the provided strings. In particular, it can now do
```
>> papis list --format '{doc[author]}\n\t{doc[title]}' -a 'einstein'  
Joshua Foer
Moonwalking With Einstein
```
while before it would print
```
>> papis list --format '{doc[author]}\n\t{doc[title]}' -a 'einstein'  
Joshua Foer\n\tMoonwalking With Einstein
```
=> Format: unescape newlines

setup.py
Installing `papis` from master to a venv and running it raises an error due to a missing `typing_extensions` library. I've added it to `setup.py` so it gets installed with `papis` through `pip`. Open to feedback!
=> Add needed typing_extensions dependency

papis/api.py, papis/config.py, tests/__init__.py, tests/commands/test_add.py, tests/test_config.py, tests/test_config_empty.py
This (hopefully) ensures that the config is properly set up in the following situations:
* no config file exists => add some default sections and libraries in there.
* no `[settings]` section exist => add one and make a best guess at a `default-library`.
* add some warnings for these scenarios so the user isn't totally surprised.
Fixes #496.
=> Fix issues around new configs

papis/document.py, papis/format.py
I added a check here in #491 which seems to have made everything twice as slow for some reason (guess `from_data` is used a lot). Oops!
Before this PR
```
Benchmark 1: papis -l papers list -a einstein
Time (mean ± σ):     508.0 ms ±  16.1 ms    [User: 2808.0 ms, System: 409.1 ms]
Range (min … max):   485.7 ms … 543.9 ms    10 runs
```
and after
```
Benchmark 1: papis -l papers list -a einstein
Time (mean ± σ):     261.2 ms ±  12.0 ms    [User: 286.3 ms, System: 144.4 ms]
Range (min … max):   248.8 ms … 291.8 ms    11 runs
```
=> papis.document: remove check in from_data

papis/database/cache.py, papis/docmatcher.py, tests/test_docmatcher.py
Following the discussion and ideas in https://github.com/papis/papis/pull/384, I've created a new potential fix for querying with the cache database and the `jinja2` formatter. This should work regardless of the actual formatter used.
=> Fix cache database query for jinja2

papis/utils.py
This also allows to skip using multiprocessing altogether. For my usual queries with about < 100 documents, using multiprocessing tends do be slower.
```
> PAPIS_NP=0 hyperfine -- 'papis -l papers export --format bibtex -a einstein'   
Time (mean ± σ):     197.7 ms ±   2.3 ms    [User: 172.9 ms, System: 24.2 ms]
Range (min … max):   196.1 ms … 205.2 ms    14 runs
```
vs
```
> PAPIS_NP=8 hyperfine -- 'papis -l papers export --format bibtex -a einstein'  
Time (mean ± σ):     249.5 ms ±   4.7 ms    [User: 280.6 ms, System: 99.8 ms]
Range (min … max):   244.1 ms … 259.7 ms    11 runs
```
EDIT: Note also that creating a `Pool(n)` with `n < 1` raises an exception.
=> Skip multiprocessing if PAPIS_NP is zero

papis/format.py
`papis.format.format` is called quite a lot (usually in loops over documents) and `papis.config.get` can be quite heavy. In some silly benchmarks, this shaved off 10ms in `papis export` and `papis list` calls.
As with all caching, this can get out of sync, but it should be fine for our use case.
=> format: cache format-doc-name

papis/database/cache.py, papis/docmatcher.py, tests/test_docmatcher.py
Was profiling some more and found some places to improve in `DocMatcher`. 
The main changes are
* store `match-format` in the `DocMatcher` class and pass it to `matcher` by default, so that `papis.config.get` does not get called in `match_document` for every `document * search`.
* post-process results from `pyparsing` into a simpler list that can be used directly in `return_if_match`, to avoid the ifs.
* store the compiled regex when post-processing, instead of recompiling it in `match_document`.
All in all, this seems to have saved another whooping 10ms-ish on my machine, bringing a call to `papis list` with about 50 / 1200 documents down to about 170ms-ish. The rest of the time is spent loading up plugins / scripts / click.
=> Minor DocMatcher optimizations

papis/commands/doctor.py, papis/defaults.py, tests/test_doctor.py
Had a lot of abstracts that contained some weird HTML / XML tags in them, so this adds a little check similar to `html-codes` to clean those up.
=> Doctor: add check for HTML tags

papis/config.py
If there are two fields with the same name in a section, `ConfigParser` throws a nasty exception. This catches that and prints a nicer message instead!
=> config: handle duplicate errors more gracefully

setup.py
`configparser` is available in the python 3 stdlib, so this is not needed anymore.
=> Remove configparser dependency

setup.cfg, setup.py
This tries to simplify the `mypy` configuration a bit.
* removes some unnecessary ignores modules that have typing annotations now.
* use explicit `strict = True` in the config instead of listing the options. This may not be a great idea because the enabled options are not stable.
=> Simplify mypy configuration

doc/source/default-settings.rst, papis/defaults.py, papis/isbn.py
This adds a new config option `isbn-service` to allow changing the service on import, e.g.
```
papis --set isbn-service goob add --from isbn 'S-OME-ISBN-CODE'
```
which defaults to `openl` at the moment.
=> Add config option for isbnlib service

papis/commands/add.py, papis/crossref.py, papis/utils.py, papis/yaml.py
This cleans up the INFO level messages printed by a bare `papis add file.pdf`. Namely:
* `utils.get_matching_importer_or_downloader`: exceptions on `match` or `fetch` are logged using `logger.debug` now, since we just want to know what importers and downloaders managed to match.
* `commands.add.run`: do not try to select importers if none matched.
* `commands.add.run`: do not log messages when `ctx` is mostly empty, e.g. if no folder or ref could be created.
Now, running `papis add 'some file that exists.pdf'` prints
```
[ERROR] commands.add: Could not produce a folder path from the provided data:
data: {'time-added': '2023-03-01-19:29:13'}
files: ['doc.pdf']
[INFO] commands.add: Folder path: '/mnt/data/docs/bibliography/papers/fd3a4a37c6d3107c398fcfc29eb5a2f9'
[INFO] commands.add: …
```
=> Improve messages for add command

papis/commands/add.py, papis/commands/update.py, papis/utils.py
This is an improvement to #387 that tries to avoid downloading files all together (and all the additional traffic!) when the right conditions are met. For this, it adds:
* a `only_data` flag to `get_matching_importer_or_downloader`
* a `only_data` flag to `get_matching_importer_by_name` (new function in `papis.utils`)
so that they only call `Importer.fetch_files` if asked. It updates `papis add` and `papis update` to use these new functions.
It probably needs a bit more testing, but it seems pretty clean. @alejandrogallo What do you think?
=> Add flag to disable file downloads

papis/commands/add.py, papis/commands/doctor.py, papis/importer.py, papis/utils.py
Mainly adds more docs and improved exception messages to `papis.importer`.
Some small behavior changes:
* took the change to refactor the `list-importer` (for `add`) and `list-checks` (for `doctor`) to use the same formatting in a nice function. The main benefit of that is that it allows having multiline docs and it just extracts the first paragraph.
* added a `@cache` to the base `Importer.fetch`
=> Improve importer docs

papis/arxiv.py, papis/bibtex.py, papis/crossref.py, papis/dblp.py, papis/isbn.py, papis/pubmed.py, papis/yaml.py, tests/test_arxiv.py
This updates remote importers to use `fetch_data` and `fetch_files` separately, so that #505 can properly skip downloading files when preferred. It's pretty much just a refactor.
* `arxiv`: the main `Importer` now has a split `fetch`.
* `crossref`: the main `Importer` also has a split `fetch`.
* `bibtex`, `dblp`, `isbn`, `pudmed`, `yaml`: just rename `fetch` to `fetch_data`.
=> Split fetch_data and fetch_files in importers

papis/importer.py
Using just the `Importer` class wasn't right because `Callable` is contravariant, so this couldn't be applied to subclasses properly. Using a nicer `TypeVar(..., bound=Importer)` now.
=> importer: use a TypeVar for the cache function

papis/commands/addto.py, papis/utils.py
* extend `create_identifier` to skip first `n` entries and use that in `addto`.
* use `handle_doc_folder_query_sort`.
* `add.get_file_name` already does `clean_document_name`, so `addto` doesn't need to.
* use `papis.api`.
=> commands.addto: some small cleanups

papis/crossref.py, papis/downloaders/__init__.py, papis/filetype.py, tests/__init__.py, tests/test_utils.py
This extends the support from `filetype` to also include DjVu files. Unfortunately upstream seems to be pretty slow (by looking at their issues / pull requests), so this should be a quicker way to go.
Added some more functions there to wrap `filetype`:
* `guess_content_extension`
* `guess_document_extension`
that work the same, but return `None` if they can't figure it out.
=> Improve support for DjVu files in filetype

papis/commands/git.py
Previously was still `run`, while now it's correctly set to `git`.
=> commands.git: name command correctly

papis/format.py, tests/test_format.py
#491 seems to have been broken because it messed around with other unicode as well. This attempts to do the dumb thing and just replace `\\n` with `\n`.
=> format: only unescape newlines and tabs

doc/source/conf.py, doc/source/developer_reference.rst, doc/source/document.rst, doc/source/index.rst, papis/document.py, papis/importer.py, papis/utils.py, papis/yaml.py
I was cleanup up some random docs lately (e.g. #532) so this adds them to the actual rendered html to make sure that everything is nice and pretty. It currently adds `papis.document`, `papis.importer`, `papis.utils` and `papis.yaml` with a big warning that these are dev docs. 
@jghauser I'm not sure where you left off with the doc re-organization, so let me know if this conflicts too much with what you had in mind. It looks something like this
=> Add a Developer API section to the docs

papis/crossref.py
This printed the DOI before actually getting the DOI from the file, causing an infinite recursion. Bug introduced in #519.
Potential improvement towards #537.
=> crossref: fix pdf2doi importer

papis/commands/add.py, papis/commands/bibtex.py, papis/commands/merge.py, papis/commands/update.py
Found this typo in `papis add --help`:
```
--link / --no-link        Instead of copying the file to the library, create
a link toits original location
```
This missing whitespace is a result of code formatting to keep line width.
A quick regex search resulted in some more strings added the same way.
=> docs: Fix missing whitespaces in CLI help texts

papis/bibtex.py, papis/commands/addto.py
Allows for two usecases:
* `papis addto -u https://example.com/paper.pdf paper`
* `papis add --from bibtex https://example.com/paper.bib`
=> Allow for http URLs where filepaths are required (`add --from bibtex` and `addto`)

doc/source/conf.py, doc/source/default-settings.rst, doc/source/developer_reference.rst, papis/cli.py, papis/defaults.py
The second commit adds the new configuration option. 
The first commit is just a bunch of documentation fixes for `papis.cli`.
Fixes #542.
=> Add config option for --reverse

doc/source/conf.py
The old way got deprecated in the recently released Sphinx 6.2, see
https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#confval-intersphinx_mapping
=> docs: update intersphinx mapping

doc/source/developer_reference.rst, papis/downloaders/__init__.py, papis/importer.py
This adds the base `papis.downloaders.Downloader` class to the developer docs. It also improves the formatting and wording in some existing docs, but not much.
=> docs: add papis.downloaders to dev docs

papis/bibtex.py
- there is no bibtex entry for bookSection
- closest option would be `inbook` (which apparently covers chapters and sections within a book
=> Added bibtex type conversion for bookSection

papis/bibtex.py
- according to [bibtex](https://bibtex.com/e/entry-types/) `masterthesis` is actually `mastersthesis`
- added conversions for `monograph`, `presentation`, `blogPost`, and `webpage`
=> A few more conversions were needed

papis/bibtex.py
This adds all the item types from https://github.com/zotero/zotero-schema to the bibtex converter.
@avonmoll Hopefully this is a bit more comprehensive now, at least as far as Zotero is concerned. Do you use other software with non-BibTeX fields that should be added?
=> bibtex: add all Zotero fields to converter

papis/commands/add.py
Tested with
```
papis add 'https://arxiv.org/abs/2305.00377'
```
and it now downloads the PDF correctly again. @alejandrogallo Does this fix it for you too?
Fixes #556
=> commands.add: fix download when remote URL is given

papis/commands/bibtex.py, papis/commands/update.py, tests/commands/test_update.py
This reworks how `papis update` handles refs:
* *before*: refs could not be modified at all.
* *after*: `papis update --set ref MyCoolNewRef <query>` modifies the ref, but importers cannot modify the ref.
@alejandrogallo This seems reasonable to me. The original `data[ref] = document[ref]` line was added in #80, but I can't think of a good reason not to allow this now. Any thoughts?
Fixes #518
=> update: allow setting the ref

doc/source/conf.py
Fixes the links in the `General settings` section of the docs pointing to non-existent URLs.
=> docs: correctly anchor config settings

papis/isbn.py, tests/resources/isbn/test_isbn_1_out.json, tests/test_isbn.py
Not quite sure when, but `isbnlib` started returning an empty language for some documents, i.e. `"Language": ""`. This sets it to English as a healthy default.
=> isbn: set a default language to English

papis/hayagriva.py, setup.py, tests/resources/hayagriva_1_out.yml, tests/test_haragriva.py, tests/testlib.py
This adds an exporter for the bibliography format supported by [`typst`](https://github.com/typst/typst) which is described [here](https://github.com/typst/hayagriva/blob/main/docs/file-format.md). It's a reasonably simple YAML format, so we just need to translate `papis` keys.
TODO:
=> Add exporter for typst bibliography format

papis/git.py
Fixes Issue #577.
I'm not sure about the position of the `import shlex`, since it's also used in the `_issue_git_command` function, but only imported in this function. Should we move the import inside the `commit` function or should we keep the import outside, and remove the import inside the `_issue_git_command`? What was the idea behind keeping the import inside the function? @alexfikl
=> fix(#577): Add shlex.quote(...) to escape string in commit bash command

papis/arxiv.py, tests/test_arxiv.py
Currently, adding arxiv papers using
```
papis add --from arxiv STRING
```
does not allow adding the `.pdf` url as a string (e.g. `https://arxiv.org/pdf/physics/0504179.pdf`).
This pull request checks if the string retrieved from the regular expression ends with .pdf and if so removes it.
It also adds tests for the new usecases as well as a more describing assertion error.
=> Feature: Allow .pdf urls to work with arxiv importer.

papis/commands/explore.py, papis/commands/external.py, papis/commands/mv.py, papis/commands/rename.py, papis/commands/run.py, papis/git.py, papis/utils.py, tests/commands/test_add.py, tests/commands/test_rm.py, tests/commands/test_run.py, tests/test_arxiv.py, tests/testlib.py
This unifies all the `subprocess` calls to a `papis.utils.run` that does the proper escaping and anything else that's needed. All commands are ported to use this.
=> Unify command calling

papis/arxiv.py, papis/bibtex.py, papis/citations.py, papis/cli.py, papis/commands/add.py, papis/commands/bibtex.py, papis/commands/config.py, papis/commands/default.py, papis/commands/doctor.py, papis/commands/edit.py, papis/commands/exec.py, papis/commands/explore.py, papis/commands/export.py, papis/commands/external.py, papis/commands/git.py, papis/commands/open.py, papis/commands/run.py, papis/commands/serve.py, papis/commands/update.py, papis/crossref.py, papis/dblp.py, papis/dissemin.py, papis/document.py, papis/isbn.py, papis/json.py, papis/yaml.py, setup.cfg, tests/test_utils.py
Ensure that all data written to YAML files is in `utf-8`.
Fixes #567.
=> windows: fix info.yaml encoding

doc/source/developer_reference.rst, papis/commands/__init__.py, papis/commands/default.py, papis/commands/external.py, papis/logging.py
This adds some clear messages about how commands are loaded. Namely:
* If two external commands have the same name, i.e. `papis-something`, but are located in different paths, a message is printed and the last one in `$PATH` is preferred. Before no message was printed.
* If an entrypoint commands, declared in `setup.py`, and an external command have the same name, the entry point is always preferred. Before the external command was preferred.
The messages are only printed with `PAPIS_DEBUG=ON`, but we can change that if we want it to be a more obvious warning (?).
=> Better command overwriting handling

.dockerignore, Dockerfile
The `test_edit.py` testcase executes itself on the command line and failed because it would not find the `tests` module. installing with `-e` seems to fix the issue. Also python 3.8 seems to be required now.
=> Updated Dockerfile to correctly execute all testcases

papis/bibtex.py, papis/commands/bibtex.py, papis/commands/browse.py, papis/commands/explore.py, papis/commands/list.py, papis/commands/update.py, papis/document.py, papis/notes.py
This adds a default or a `try..except` for most of the calls to `papis.format.format` after #596.
=> Handle papis.format exceptions

flake.nix
Two of my usecases are covered with this `flake.nix` (based on the code from nixpkgs itself):
1. `nix develop` - quickly set up a development environment using the `nix` package manager (actually also sets up a venv to get some of the typing packages).
2. "Install from main" with `nix profile install '.#papis'` if you have cloned the repo, or also `nix profile install 'github.com:papis/papis#papis'` should work.
=> Added `flake.nix` to enable usage with the nix package manager.

tests/commands/scripts.py, tests/commands/test_edit.py, tests/commands/test_open.py
The edit test at `commands/test_edit.py` was calling itself to modify a `info.yaml` file for testing purposes. This moves that code to a separate file to not require editable installs (see #597).
=> Fix tests calling themselves

papis/crossref.py, papis/document.py
Along the way fixed format string that contained a '%s' without corresponding arg.
=> Avoid exception when parsing crossref event data that has no 'start' key

papis/defaults.py, papis/utils.py, tests/commands/test_open.py, tests/test_config.py
Updates `general_open` to actually work with the default `start` command on Windows. 
Seems like that needed `shell=True` because it's an internal shell command. This changes the default to call `cmd.exe /c start` instead.
Fixes #568.
=> windows: fix opentool usage

papis/arxiv.py, papis/bibtex.py, papis/cli.py, papis/commands/add.py, papis/commands/bibtex.py, papis/commands/config.py, papis/commands/default.py, papis/commands/doctor.py, papis/commands/edit.py, papis/commands/exec.py, papis/commands/explore.py, papis/commands/export.py, papis/commands/external.py, papis/commands/git.py, papis/commands/open.py, papis/commands/run.py, papis/commands/serve.py, papis/commands/update.py, papis/crossref.py, papis/dblp.py, papis/dissemin.py, papis/isbn.py, papis/json.py, papis/yaml.py, setup.cfg
This reverts the `type: ignore` for click added in #571. Click fixed all those issues in version 8.1.6 (so 8.1.4 and 8.1.5 only are broken for mypy).
It also fixes a new issue with `commands.default.MultiCommand`: turns out `click.group(cls=GroupType)` expects a Group subclass, not a MultiCommand subclass.
=> Revert mypy ignores

papis/commands/cache.py, papis/commands/serve.py, papis/defaults.py, papis/fzf.py, papis/tui/app.py, papis/tui/picker.py, papis/tui/utils.py, papis/tui/widgets/__init__.py, papis/tui/widgets/command_line_prompt.py, papis/tui/widgets/diff.py, papis/tui/widgets/list.py, setup.cfg, setup.py, tests/commands/test_cache.py
This was a chunk of code that was not getting checked before. This fixes all the `mypy` errors in there and and makes the remaining `type: ignore` have an actual error code attached so we catch new errors.
=> Fix mypy errors in papis.tui

papis/commands/update.py, papis/crossref.py
--batch option set _all to True (avoid the menu asking to manually select the entries to update if multiple matches)
=> crossref: remove use of interactive pick_doc

papis/commands/__init__.py, papis/commands/bibtex.py, papis/commands/cache.py
I noticed this with the `papis cache` command, which had subcommands with longer help texts that would show up as e.g.
```
Commands:
update        Reload the yaml file from disk and update the cache with...
```
This change teaches `AliasedGroup` to wrap the text and it looks like
```
Commands:
update        Reload the yaml file from disk and update the cache with that
information.
```
I also updated the text to be shorter since that looks nicer. The full help text can still be seen when running e.g. `papis cache add --help`.
=> Wrap help text in AliasedGroup

.readthedocs.yml
The readthedocs builds have been failing recently:
https://readthedocs.org/projects/papis/builds/21604354/
Not quite sure what brought that on. From a bit of googling, the error seems to be due the `sphinx_rtd_theme` not supporting Sphinx v7, but those should be fixed and updated already.
This bumps the image used by RTD to the latest versions to see if that helps at all, but generally not sure what's going on :\
=> rtd: bump image to python 3.11

setup.py
Another try at fixing the RTD build. From the logs
* passing: https://readthedocs.org/api/v2/build/21470845.txt
* failing: https://readthedocs.org/api/v2/build/21604657.txt
it seems like it's not installing a newer `sphinx-rtd-theme` anymore. This forces a newer version in the hopes that it will download it again.
=> setup: add lower limit to sphinx-rtd-theme

papis/cli.py, papis/commands/add.py, papis/commands/bibtex.py, papis/commands/browse.py, papis/commands/citations.py, papis/commands/config.py, papis/commands/default.py, papis/commands/doctor.py, papis/commands/edit.py, papis/commands/explore.py, papis/commands/export.py, papis/commands/list.py, papis/commands/merge.py, papis/commands/open.py, papis/commands/rm.py, papis/commands/update.py
This tries to make issues like #634 less likely.
Just to add a bit of context: `click.option` based flags can have other values besides the boolean `True`/`False` and the default value is given by `flag_value`. If the `flag_value` is not provided, it is set to `not default`, which in the case where `default` is a callable is always false.
TO get around that, this adds a wrapper `papis.cli.bool_flag` specifically for boolean flags like we use throughout that always sets `flag_value`. Hopefully will make it less likely to hit an issue like that.
=> Fix click flags default

papis/commands/doctor.py
`input` only stops on Enter while `click.pause` stops on any key pressed.
=> commands.doctor: use click.pause instead of input

flake.nix, papis/arxiv.py, setup.cfg, setup.py, tests/test_arxiv.py
This switches the arxiv code to use [arxiv.py](https://github.com/lukasschwab/arxiv.py). Some benefits:
* it seems better maintained ([arxiv2bib](https://github.com/nathangrigg/arxiv2bib) was last updated in 2017),
* it allows removing our custom `bs4` based parsing,
* the API generally seems nicer.
=> Use arxiv.py instead of arxiv2bib

papis/bibtex.py, papis/dblp.py, papis/document.py, papis/downloaders/base.py, tests/test_document.py
@f0rki Cherrypicked from #598. There is one change though: the `guess_authors_separator` function always returns a string so that the single author case doesn't need a special `if` every time.
I imagine this heuristic will need tweaking over time, but it looks pretty useful already.
=> document: add heuristics for splitting authors

doc/source/default-settings.rst, papis/commands/doctor.py, papis/defaults.py, tests/test_doctor.py
This builds on #652 and adds some extra functionality when dealing with `list -> str` or `str -> list` conversions.
@jghauser What do you think? Could this be used to "fix" tags? i.e. something like this could be used to split them up
```
papis --set doctor-key-type-separator ', ' doctor --check key-type --fix QUERY
```
I added some test cases for that specifically and it seems ok. Did you have other formats in mind?
=> commands.doctor: add separator to key-check

doc/source/default-settings.rst, papis/commands/browse.py, papis/defaults.py
A very small improvement: adding a 'browse-key' auto which allows the program to cleverly choose by itself the key if the document["url"] is not found. A step more on the road of the full automation of papis...
=> commands.browse: add browse-key auto option

papis/document.py
Previously `doc.copy()` would return a bare `dict`. This fixes it to return a `Document` with a main folder.
=> document: implement copy

papis/commands/doctor.py
Added some colors to the output (that largely match what's in `papis.logging`). It looks like this in my terminal
@jghauser What do you think? For a lot of errors, the output was hard to parse at a glance, so I thought some colors would do it good!
=> commands.doctor: add some colors to the output

papis/bibtex.py, papis/commands/doctor.py, papis/document.py
Had this sitting around for a while because I needed to clean some documents with weird / missing fields that BibLaTeX didn't like. It adds 3 new checks to `papis doctor`:
* `biblatex-type-alias`: some BibTeX types are defined mostly for backwards compatibility, so this check looks for them and updates them to modern variants.
* `biblatex-key-alias`: same for BibTeX keys / fields.
* `biblatex-required-keys`: the BibLaTeX manual defines some required keys for each type, e.g. an `article` requires `("author", "title", "journal", "year")` at the least. This checks and warns about missing keys in the document.
None of these are turned on by default, so hopefully they're ok to add for anyone who wants a more BibLaTeX friendly library :grin: …
=> Add BibLaTeX doctor checks

doc/source/default-settings.rst, papis/defaults.py, papis/format.py, papis/utils.py, setup.py, tests/test_format.py
This changes to the correct spelling "formatter" everywhere and adds a bunch of deprecation warnings and safeguards. Will need to test a bit, but it should be safe.
@jghauser Better? :grin:
=> format: fix spelling formater vs formatter

papis/config.py
It would always say `'<value>' is a 'str'`, which is not very helpful. (it was just some copy pasting mistake)
=> config: fix exception text

doc/source/default-settings.rst, papis/commands/doctor.py, papis/defaults.py, tests/test_doctor.py
This changes the configuration setting of `doctor-key-type-check-keys`
```
from: [("year", "int"), ("files", "list")]
to:   ["year:int", "files:list"]
```
with the goal of removing the `eval` usage. 
* Changing from a tuple `("year", "int")` to `"year:int"` allows easier parsing without eval.
* Using `getattr(builtins, cls_name, None)` instead of eval. This should also enforce that the types are builtin Python types.
@alejandrogallo Did you have any fancier types in there that would require an `eval`? What do you think about this?
=> commands.doctor: change key-type check to avoid evals

papis/commands/add.py, papis/commands/update.py, papis/utils.py
This just updates some functions in `papis.utils` to have better named arguments that are in line with #641.
=> Use better names for only_data arguments

papis/commands/init.py, setup.py
I think we would benefit of having a clearer workflow for newcomers
when initializing a library.
Something similar to git would be a better initiation for kickstarting
a papis library.
This is a pull request / discussion to decide what is the best way
forward in this.
For now, you go to the dir
```
mkdir -p ~/Documents/papers
cd ~/Documents/papers
```
and you can then
```
papis init
```
and interactively answer the questions being prompted.
This then updates the configuration file.
You can use the `init` command to then change more options
in the future.
Also it can be a good gateway to tell users
about the most useful configuraiton settings, and they can set them
righ away.
=> Tentative implementation of papis-init

doc/source/commands/doctor.rst, doc/source/conf.py, doc/source/developer_reference.rst, papis/commands/doctor.py
This adds all the doctor check functions to the docs, so they can be more easily looked through.
=> docs: add commands.doctor to the dev docs

papis/commands/init.py
This makes all the setting prompts in `papis init` be in a form of a short question.
=> commands.init: unify style for setting help messages

papis/commands/init.py
* Makes the initial warning a bit less scary by explaining what could change in the config.
* Adds a few more links at the bottom to github.
=> commands.init: extend logger messages

papis/commands/init.py
Apparently `papis.tui.utils.prompt` already adds a space for the default option, so this looked like
```
before >> Path to library:  (papers):
after  >> Path to library (papers):
```
=> commands.init: remove extra space from prompts

papis/commands/init.py
Adds a list of known libraries to `Name of the library` so the user can avoid overwriting libraries.
=> commands.init: add some bottom_toolbars to the library names

papis/commands/add.py, papis/commands/rm.py, papis/document.py, papis/tui/utils.py, tests/commands/test_add.py, tests/test_arxiv.py, tests/test_document.py
After #616, `papis add` would no longer show any information about the document being added. Before it just showed the results of a diff with the importer data, so if there was no importer it also wouldn't show anything. This prints out the document on purpose before asking for confirmation. On my system it looks like:
@jghauser I tried to make this look like the resulting `info.yaml` file and use similar styling to `tui.widgets.diff` (mainly the black background). What do you think? I mostly wanted it because it can happen that the metadata isn't correct (hit this with the `isbn` importer especially) and it's nice to see beforehand.
=> commands.add: show document before adding

papis/utils.py
Removed this in #672, but had some plugins that used it and the removal confused mypy :(
This does the nicer thing and adds some backward compat, at least until the next release. `only_data` is not documented or anything, since it's supposed to be deprecated.
=> utils: re-add only_data kwarg for backwards compat

papis/filetype.py, papis/testing.py, tests/database/test_database.py, tests/database/test_papis.py, tests/database/test_whoosh.py, tests/test_format.py
This updates the testing module to
* Temporarily monkeypatch cached globals like `papis.format.FORMATTER` and `papis.database.DATABASES`, so that the tests don't need to.
* Support parametrizing fixtures using the `indirect=True` keyword, which is used to set the `database-backend` before entering the test.
=> testing: reset some globals

doc/source/conf.py
My url resolution didn't seem to work on readthedocs, so this tries again :crossed_fingers: using `obj.__module__` instead of the path.
=> docs: fix linkcode url resolution

papis/cli.py, papis/commands/add.py
Before it was just using `bool(get("use-git"))`, which would be true if `use-git = false` (only way to make it false would be to not add it to the configuration file).
Fixes #698.
=> cli: use getboolean to get use-git option

doc/source/commands/config.rst, doc/source/configuration.rst, papis/format.py
This updates the `configuration.rst` file:
* Cleans up some phrasing here and there.
* Adds a mention to the `papis config` command so users can check settings.
* Adds a warning about the formatter, which is a big part of some configuration settings.
Fixes #704.
=> docs: update configuration docs

papis/commands/add.py, papis/commands/addto.py, papis/commands/doctor.py, papis/commands/update.py, papis/database/cache.py, papis/defaults.py, papis/testing.py, papis/web/docview.py, tests/commands/test_add.py, tests/test_doctor.py
Introduced a new option auto-doctor wich controls whether `papis doctor` is run on each `add`'ed|`update`d document. The idea is to automatically ensure that documents are consistent to what we expect.
(However, this flag is currently disabled by default, because it breaks a lot of tests by being on by default.)
Introduced two new config options:
* `auto-doctor = False` - whether to run doctor on all documents always
* `auto-doctor-edit = False` - whether to launch the editor on documents that cannot be fixed automatically.
* `papis (add|update) (--auto-doctor|--no-auto-doctor)` to enable/disable
auto-doctor on the fly.
Extended the `key-exists` check with an "Autofiller" mechanism that automatically fills in missing keys. Implemented autofillers for filling `author` and `author_list` if …
=> Added "auto-doctor" setting to automatically apply papis doctor to new documents

papis/bibtex.py, tests/commands/test_explore.py, tests/test_bibtex.py, tests/test_doctor.py, tests/test_document.py
Not sure why the references were forcefully capitalized, but this removes that to allow lowercase refs.
@hermlon This should fix that issue.
=> bibtex: do not forcefully capwords references

doc/source/default-settings.rst, papis/bibtex.py
This adds some links to `papis.bibtex.ref_cleanup` to the `ref-format` docs so that users know that their resulting references may be slightly different.
=> docs: clarify ref-format additional cleanup

doc/source/default-settings.rst, papis/commands/doctor.py, papis/defaults.py, tests/test_doctor.py
This adds a new doctor check for duplicates inside a list. The intended use case was to check if the same file was added multiple times / the same tag was added multiple times / the same author was added multiple times, etc.
@jghauser Inspired by some of your work on the update command.
=> doctor: add check for duplicate entries

papis/commands/list.py
=> commands.list: show main_folder by default again

papis/bibtex.py
This adds the extra types and fields from [biblatex-software](https://ctan.org/pkg/biblatex-software?lang=en). 
I was looking at a nicer way to add software entries to a bibliography and this seemed to be used and maintained. We don't currently have a way to import software entries, but it would be cool to add something based on the Software Heritage Archive in the future!
=> bibtex: add types from biblatex-software

papis/bibtex.py
This ignores any `file` entries when outputting to BibTeX. Those shouldn't be in there anyway and are handled by the `bibtex-export-zotero-file` setting instead.
xref: #721
=> bibtex: ignore any file entries by default

doc/source/default-settings.rst, papis/bibtex.py, papis/defaults.py
This deprecates `bibtex-export-zotero-file` in favor of just `bibtex-export-file`, since it doesn't necessarily have anything to do with Zotero.
xref #721
=> bibtex: rename bibtex-export-zotero-file without zotero

papis/commands/doctor.py
This checks if a `file` key is is in the document and warns about it. We mostly use `files`, so this would have sneaked in by mistake!
We could add a fixer too, but it would need to know whether to copy / link / move the file, so that's not implemented at the moment.
xref #721
=> doctor: add check for single file key

doc/source/default-settings.rst, papis/commands/serve.py, papis/defaults.py, papis/web/tags.py
This adds two further Options besides the refresh icon to select whether to sort the list of tags alphabetically or by their number of occurrences. Formerly, the latter was the default and only option.
Why? I use tags a lot and found myself frequently searching for them on the page. Alphabetical sorting makes that much easier.
=> papis.serve: add sorting options to the tags endpoint

papis/commands/doctor.py, tests/test_doctor.py
This adds a simple fixer for the `bibtex-type` doctor check using `bibtex_type_converter`.
=> commands.doctor: add a fixer for bibtex-type

setup.py
Bibtexparser 2.x will not expose latexenc module
=> bibtex: more strict version for bibtexparser (#738)

flake.nix
I'm quite new to nix, so not sure if this is correct. I'd love some input from fellow nix users @f0rki or @alejandrogallo.
This PR would solve 2 things:
1. I've been installing papis on my system via the flake and that worked for a while. However, at some point it broke:
```
error: builder for '/nix/store/cxcc2ihfxipsjpy3r8fxrqvz0zdph283-python3.10-papis-0.13.drv' failed with exit code 1;
last 10 log lines:
> Running phase: updateAutotoolsGnuConfigScriptsPhase
> Running phase: configurePhase
> no configure script, doing nothing
> Running phase: buildPhase
> Executing setuptoolsBuildPhase
> Traceback (most recent call last):
>   File "/build/khp02d3wb2lb6z0nb5wa2d21p46fhzkm-source/nix_run_setup", line 3, in <module>
>     import setuptools
> ModuleNotFoundError: No module named …
```
=> Improve flake

flake.nix, setup.py
Not quite sure why this wasn't added as an optional dependency, but it should definitely be in there.
=> setup.py: add jinja2 optional dependency

papis/format.py, tests/test_format.py
This implements a special Formatter for our `PythonFormatter`
https://docs.python.org/3/library/string.html#string.Formatter
that supports some extra operations to make it slightly less likely to switch to the `jinja2` formatter:
* It adds `l`, `u`, `t` and `c` conversions for `lower`, `upper`, `title` and `capitalize`. It also adds a `y` conversion that calls `slugify`! Format strings using these look like
```
"{doc[title]!t}"
```
* It adds a funky formatting spec `S` that can select words from a string. This basically does `" ".join(value.split(" ")[istart:iend])`. It looks something like this to selects words 1 to 3
```
"{doc[title]:1.3S}"
```
@alejandrogallo @jghauser This was mostly an experiment because I stumbled upon that `Formatter` class (didn't know it existed). What do you …
=> Enhance python formatter with extra conversions

doc/source/bibtex.rst, doc/source/conf.py, doc/source/configuration.rst, doc/source/database_structure.rst, doc/source/default-settings.rst, doc/source/developer_reference.rst, doc/source/git.rst, papis/bibtex.py, papis/citations.py, papis/commands/add.py, papis/commands/bibtex.py, papis/commands/browse.py, papis/commands/doctor.py, papis/commands/edit.py, papis/commands/list.py, papis/commands/open.py, papis/docmatcher.py, papis/document.py, papis/format.py, papis/notes.py, papis/pick.py, papis/sphinx_ext.py, papis/utils.py, setup.cfg
This improves how configuration values are handled in the docs:
* It adds a new directive `:confval:` that's used by the wrapping `papis-config` directive to render the configuration values in a nicer way.
* Adds a `type: ...` entry to each config to show what type we expect it to be.
* They can now be referenced normally using `:confval:<name>` just like `:class:` or `:func:` roles.
It also moves the Sphinx directives from `docs/source/conf.py` to `papis/sphinx_ext.py` so that they can be used by external plugins without copy-pasting them. And for some pretty pictures before and after:
Before:
After:
=> docs: improve how configuration values are handled

.codespell-ignore, Makefile, examples/scripts/papis-abbrev, examples/scripts/papis-check, examples/scripts/papis-mail, papis/arxiv.py, papis/commands/default.py, papis/database/base.py, papis/document.py, papis/sphinx_ext.py, papis/utils.py, tests/commands/test_cache.py, tests/test_utils.py
This adds a simple codespell target to the Makefile and fixes all the spelling errors that it reports. There's just a few though, so not a big change.
=> Fix spelling errors

papis/commands/doctor.py, papis/commands/update.py, papis/defaults.py, papis/testing.py, tests/commands/test_export.py, tests/commands/test_update.py, tests/resources/hayagriva_1_out.yml
OK, here it is! This has taken a while and turned out to be a bit more complex than I anticipated. Given the many different ways of using it, there are bound to be errors lurking in it still. I'd appreciate if you could try out your various use cases and let me know how it's going. Tests are also still missing...
I've left a bunch of comments throughout (indicated with `TODO` and such) regarding things that I wasn't sure about. Let me know what you think. I'm sure I've also done some things in a silly/hackish way -- I would appreciate any feedback!
I've got another PR coming with the `papis tag` command. It's basically done as it'll be super simple given that it'll be using all the logic from `papis update`. At the moment, I'm importing `papis.commands.update` but I can also move the …
=> Update the update command

HACKING.md, flake.nix
I've been wanting a container in which I can try out various commands and see how they work. Which is why I made the below small script number 3 for my development shell. While I was doing that, it seemed logical to also create 1 + 2:
1. `papis-build-container` (builds the container)
2. `papis-run-container-tests` (runs the tests in the container)
3. `papis-run-container-interactive` (drops you into a shell in the container after populating the library)
The commands use `podman` or `docker`, depending on which is in the path.
I could also make these individual scripts so that they would be available for non-nix users, if there is a desire for that.
=> add convenience commands to nix flake

papis/commands/tag.py, setup.py, tests/commands/test_tag.py
This is a draft of a new `papis tag` command that allows adding/removing/clearing tags. There are some docs inside to show you what's possible.
This is mostly just a first working draft to get some feedback. Here are some questions/considerations I'm unsure about:
- Is this a useful thing to ship with papis? We already have `papis update` that can do some of what `papis tag` can do. Is there too much overlap? Should this maybe rather be an additional script?
- What functionality would you like to see? Maybe it could be useful to apply all tags from one doc to another for instance...
- Better idea for the names/structure of the options? For instance I would have liked to use `--add` for adding tags, but the short version of that is `-a` which is already used by `--all`. I've also …
=> Add `papis tag` command

papis/commands/addto.py, papis/utils.py, tests/commands/test_addto.py
In `addto` we would always add the previous suffix incorrectly, e.g. if there's no file it would add an `-a`, if there's one file it would add a `-b`, etc.
xref: https://github.com/papis/papis/discussions/762#discussion-6294918
=>  commands.addto: add expected suffix

papis/testing.py, setup.cfg
This adds a `conftest.py` with a little fixture to the root `papis` folder. It's meant to run the doctests in a clean configuration (not the one in the user's `~/.config/papis`)
@alejandrogallo It's a little hacky to add a test file to the package folder, but it should help users run and pass the tests (if not using a docker container or similar). What do you think?
Fixes #757.
=> tests: add a fixture for doctests

tests/test_config.py
I saw a very minor improvement that ruff caught:
There was a comparison that was performed instead of checking the instance.
This change makes ruff happier.
Also, this is my first of many (I hope!) commits to papis, so :wave: !
=> refactor(tests/test_config): check instance instead of comparing

papis/sphinx_ext.py, setup.py
We're pulling in `types-docutils` through `types-Pygments`, which started giving some typing errors.
=> fix: mypy errors from types-docutils

papis/importer.py, tests/test_importer.py
Hi!
I noticed during my PR for Zenodo that, in order for an `Importer` to store stuff that had to survive different calls (say, `fetch`, then `match` or whatever), you had to add custom attributes into `self`. That's what `arxiv` [is currently doing](https://github.com/papis/papis/blob/b3ada0efcf16c2d0272c5f79858659629634a22b/papis/arxiv.py#L346).
In [this comment](https://github.com/papis/papis/pull/770#discussion_r1518578728) it was proposed that perhaps there should be a way to let Importers store additional attributes.
Is that what `Context` is for?
In my importer, [you can see](https://github.com/papis/papis/pull/770/files#diff-740a873f36cf874d9d4c3f9842878e2c79d241f52f7510defd1857ac8a8b7e9fR146) I try to use the context to store data that is for internal use.
But the current …
=> Support custom context for importers

papis/downloaders/__init__.py, setup.py
@kiike Tried to play around a bit with the Zenodo importer and noticed it didn't have an entrypoint set. How did you test it?
Also found a little bug: the filename from Zenodo could be a relative path e.g. `username/filename.zip`, in which case just writing the file wouldn't work because the folder does not exist. I modified it to just use the basename instead.
=> Add zenodo entrypoint

pyproject.toml
Oops, was a bit quick with the `shared-data` thing and didn't write it correctly: it requires the file name in the target location as well.
xref: #607
=> pyproject: fix shared data

flake.nix
Quick improvement to the `flake.nix` to use `shortRev` consistently
=> flake: use shortRev

papis/database/cache.py, papis/docmatcher.py, papis/testing.py, pyproject.toml, tests/database/test_papis.py, tests/test_docmatcher.py
@jghauser This should hopefully fix the issues you were seeing. I added a `~/.config/papis/config.py` with just `raise RuntimeError` and it's never loaded now. 
* The first commit adds a little hack so that we don't hit this anymore, by setting `XDG_CONFIG_HOME=/tmp` before any tests run. This is under a `--tmp-xdg-config-home` flag so that we can check if any test breaks things.
* The second commit fixes our tests so that they don't call `papis.config` before we have a chance to construct a `TemporaryConfiguration`.
The second commit should make it so that the tests still work even if we don't add the `--tmp-xdg-config-home` flag to `pyproject.toml`. Let me know if you get a chance to test it!
Fixes #784.
=> Fix tests picking up config.py

.github/workflows/nix-flake.yml
It doesn't in this case fail without it, but as #786 shows it's sometimes necessary and we don't wanna unnecessarily ask for trouble
=> ci: run nix pytest with `python -m`

HACKING.md, PACKAGING.md, doc/source/testing.rst, papis/testing.py, pyproject.toml
This adds some additional warnings to the testing docs to mention the new flags that enable running the tests in a clean environment.
@jghauser Added some more context to `docs/source/testing.rst` about those flags and why they're there. Let me know if you think anything else would be helpful to mention! I also renamed them to make it clear they're papis-specific.
xref: #786 #758.
=> docs: update testing docs

papis/downloaders/thesesfr.py, pyproject.toml, tests/downloaders/test_thesesfr.py
That `--ignore` line in the pytest config made me sad. I went to see what happened with that downloader. I fixed the tests and the downloader so we can now read more French.
As a small bonus, you can now also download files using only the id: `papis add 2019REIMS014`.
=> fix(thesesfr): update to support the new API

.github/workflows/windows.yml, pyproject.toml, scripts/windows/papis.spec, scripts/windows/run.py
This pull requests allows for creating Papis one-file binaries that can be run under Windows without needing the Python toolchain installed.
Right now it works OK, a bit slower compared to a one file+support dir, but maybe this is alright. Besides changing the version identifier so it mentions the commit ID that triggered the rebuild, I tried to touch the minimal things to build this:
- the pyproject.toml now has a windows dependency group that is used by the action. If needed, I could move it to the action, but here it's a bit more explicit if somebody wants to build this on-prem.
- there is a new action workflow now, called "Build windows release". Right now, it will run on PR and pushes on main, allowing to test binaries for commits that trigger these events. This action needs two more …
=> ci: build windows executables

papis/commands/default.py, papis/commands/init.py, papis/config.py, papis/database/cache.py
This should fix some issues when working with a new configuration file:
* Calling `papis add --help` (and all other) no longer shows a traceback, but a nicer error message.
* `papis init` can be used without crashing horribly too.
* Removed logging messages in `Configuration.initialize` because they weren't showing up correctly anyway.
Fixes #697.
=> commands.init: improve first-time usage and messages

doc/source/commands/tag.rst, papis/commands/tag.py, papis/commands/update.py
I realised the tag and update docstrings didn't use rst synatx. Also the stub to create docs from the tag docstrings were missing.
=> fix docs for update and tag command

papis/commands/update.py
When I was calling `papis -l update --all --set ref '{doc[author_list][0][family]!l}_{doc[year]}_{doc[title]!l:0.3S}'`, I noticed that `doc[title]` had spaces in it that were not being cleaned up. This seemed like the appropriate fix, since `ref_cleanup()` is called other times when `ref` is being set.
=> Call `ref_cleanup()` function when `papis --set ref` is called

CHANGELOG.md, papis/config.py, papis/database/cache.py, papis/database/whoosh.py, papis/testing.py, papis/utils.py, pyproject.toml, tests/test_config.py, tests/test_utils.py
This switches to using [platformdirs](https://platformdirs.readthedocs.io/en/latest/) for all our "getting a standard path" functions. This will mainly improves the situation on other platforms, i.e.
* On Windows the configuration should go in `%USERPROFILE%\AppData\Local\$appauthor\$appname`
* On macOS the configuration should go in `~/Library/Application Support/$appname/$version`
To help with migrating:
* config: When loading a config, it checks if the previous XDG-based `config_folder` exists and copies it over with a warning.
* cache: Nothing is done here, since we can just regenerate the cache and nothing is lost. It's not too hard to copy over older caches, so I'm open to suggestions.
On Linux, this shouldn't change anything at all really, so if someone with a different OS can …
=> config: use platformdirs

doc/source/default-settings.rst, papis/defaults.py, papis/utils.py, tests/test_utils.py
This adds three options to configure the behaviour of slugify when cleaning document paths:
- ``slugify-lowercase``
- ``slugify-regex-pattern``
- ``slugify-separator``
Their effects mostly follow the respective arguments to ``python-slugify``. Hopefully appropriate documentation about this is added to ``default-settings.rst``.
As this is my first PR for this project any feedback is welcome and greatly appreciated!
=> add slugify configuration options

tests/commands/test_edit.py
When testing #813 I found a minor bug that happened on Windows during testing in CI or in my machine with a vanilla Windows installation.
The venv with uv is not global, so `test_edit_run` fails because the mock sed program does not have the necessary papis dependency, not being aware of the local venv.
With this PR, the interpreter is made to be the one that runs during CI (using `sys.executable`), having access to all the runtime dependencies.
=> tests/mock_sed: use same interpreter as the one `pytest` is running

papis/commands/rename.py, papis/git.py, tests/commands/test_rename.py
When I develop a feature, I try to dogfood, so sometimes I end up using default values of config options such as `add-folder-name`, thus creating folders that don't end up like I like. `papis rename` can rename entries but is now pretty limited.
With this WIP pull request, I am trying to make `papis rename` a bit more powerful:
- allow selecting multiple entries with the picker
- selecting all entries matching a query, for mass renaming of folders
- optional slugify of names
- rename without confirmation
- rename using the generated folder name
It's taking form:
With slug enabled:
```
 papis rename -arsb "black hole"
[INFO] commands.rename: Renaming 'raju-2024-howdoesinformationemerge' into 'test-2024-how-does-information-emerge-from-a-black-hole'
[INFO] commands.rename: Renaming …
```
=> feat(rename): allow batch and auto-renaming from pattern

papis/commands/add.py, papis/commands/addto.py, papis/commands/mv.py, papis/utils.py, tests/commands/scripts.py, tests/commands/test_add.py, tests/commands/test_edit.py, tests/commands/test_open.py, tests/commands/test_run.py
When I was developing an earlier PR, I wanted to test it on a vanilla installation of Windows, just to make sure no config could pollute the results.
Turns out, some tests fail on this kind of setup. Even with a benign but creepy Windows error popup during `tests/commands/open`.
Some reasons for the failing tests:
- symlinks no functional unless "developer mode is active" (I guess CI never sees this because it's running a modified build)
- typical unix commands such as `mv`, `echo` or `mv` not present in vanilla Windows.
Some details of this PR:
- It actually contains a fix that is present on a commit of #810, so I'll remove it from there.
- I want to explain the user why symlinks don't work if we get an exception.
- I'm sad to make `["git"] if git else []) + ["mv", folder, …
=> tests(windows): fix remaining "unixisms" that break some tests

papis/tui/__init__.py, papis/tui/app.py, papis/tui/widgets/list.py
One of the things that I found a bit unintuitive in the picker was that marked lines only had one marker on the first line. That is alright but I find it a bit more straightforward if the marker is applied to the whole entry, as many lines as that might span.
Also, while both selected and unselected margins can be configured, marked margins can not. I use the marker quite often, so i want a clearer picture of what I have marked.
This PR introduces:
- configurable marked line margin style: allows setting the style of a marked entry's margin ![image](https://github.com/papis/papis/assets/464625/3a82545b-c688-4d47-b805-71949fb02c6c)
- markers span the whole line range for an entry instead of just the first line. ![image](https://github.com/papis/papis/assets/464625/bea14ba2-fe96-4398-b7ca-057 …
=> picker: some minor improvements for marking entries

CHANGELOG.md
This was in #711 and kept causing conflicts :(
=> docs: update phrasing in changelog

doc/source/conf.py, papis/sphinx_ext.py
Plugins using this may not use `linkcode`, so it's not nice to require it.
=> sphinx_ext: do not require linkcode

papis/commands/serve.py
This makes all the imports to `papis.web` in `commands.serve` local to the function that's calling them.
The main motivation for this was to make `dominate` optional from a packaging perspective. It's now only needed when running the `papis serve` command, not when loading the plugin for it.
=> commands.serve: make web imports local

doc/source/bibtex.rst, papis/bibtex.py, papis/commands/bibtex.py, papis/commands/explore.py
I used the `papis bibtex` command recently and did some small cleanups along the way. Some small functionality changes as well:
* `papis bibtex update --to`: actually implement this flag, but haven't tested it.
* `papis bibtex open`: shows a nicer error message instead of raising an exception on failure.
=> commands.bibtex: some general cleanup

doc/source/configuration.rst, papis/commands/addto.py, papis/commands/edit.py, papis/commands/open.py, papis/config.py, papis/testing.py, tests/commands/test_edit.py, tests/commands/test_open.py, tests/test_config.py, tests/test_utils.py
This fixes the tests so that they work when the temporary path contains a `%`. It also adds a nicer error message in `papis.config.set`.
@hseg If you have a chance to test this, that would be great! I tried running the whole test suite with a percent in the tmpdir and it worked for me.
Fixes #850.
=> config: handle percents in file paths

papis/config.py
This should allow setting libraries in `config.py` using `register_default_settings` dynamically. Something like this should now work as expected
```
import pathlib
from papis.config import register_default_settings
basedir = pathlib.Path('/home/user/Documents')
register_default_settings({
**{subdir.stem: {'dir': str(subdir)} for subdir in basedir.glob('[a-z]*/')},
**{"settings": {"default-library": "lib1"}}
})
```
xref: #851
=> config: allow libraries in default-settings

doc/source/default-settings.rst, papis/commands/default.py, papis/defaults.py, papis/pick.py
This adds a little wrapper to pick libraries (e.g. `papis --pick-lib add`) with more color. On my dark terminal it looks something like this
@jghauser I'm not sure if there is any other nice information we could display about the libraries. Any thoughts?
=> pick: add nicer library picker

doc/source/default-settings.rst, papis/commands/doctor.py, papis/defaults.py, tests/commands/test_add.py, tests/test_doctor.py
This renames the `keys-exist` check to `keys-missing` with a bunch of deprecation warnings.
@jghauser What do you think about this? Should we also change the default to `biblatex-required-keys` for smarter missing key reporting?
Fixes #849.
=> commands.doctor: rename keys-exist to keys-missing

papis/commands/doctor.py
The `biblatex-required-keys` check was using the `bibtex-type` check to make sure that the document actually has a type first. Unfortunately, if both checks are in `doctor-default-checks`, the same error would be reported twice.
This ensures that the errors have the expected name, i.e. it replaces the name of the errors coming from `bibtex-type` so that they show up as `biblatex-required-keys` errors.
=> commands.doctor: fix incorrect check name

papis/commands/update.py
As suggested by @kiike, I improved the docs around ``papis update`` python expression parsing. I moved the example covering this feature to the very bottom and added a note that this is an advanced feature.
=> docs(update): improve info re python expression parsing

papis/commands/doctor.py, tests/test_doctor.py
As stated, this allows the `html-codes` doctor check to also fix weirdly uppercased codes like `&Amp;`. Not sure how I managed to get one of those, but it's a pretty easy fix..
=> commands.doctor: also support weirdly uppercased HTML codes

papis/isbn.py, tests/resources/isbn/test_isbn_1_out.json
The `isbn` importer did not set a type for the document because `isbnlib` does not provide one. This forces all documents to be books, since that's what `isbnlib` does too in its BibTeX exporter.
=> isbn: force book type for data from isbnlib

papis/document.py
Clear current data (if any) in the document before loading new data in document.load().  This avoids an edge case where a document is being updated, and a key is removed.
Closes #895
=> document: Clear dictionary before loading data

papis/commands/add.py, papis/commands/addto.py, papis/downloaders/__init__.py, papis/paths.py, tests/downloaders/test_utils.py, tests/test_paths.py
This tries to be a bit smarter about adding suffixes to files in `papis add` and `papis addto`. Namely:
* Unifies the two with a new function `papis.paths.rename_document_files`.
* Makes files with different extensions not get a suffix, e.g. if one adds `file.pdf` and `file.md` it will now not rename them like `<something>.pdf` and `<something>-a.md` (with the `a` suffix).
=> feat: tweak document file naming

papis/document.py, tests/test_document.py
This was hardcoded to use python formatting. Oops!
Fixes #905.
=> Use papis.format in author_list_to_author

papis/defaults.py
With the new tag command, add only works if it's a list. papis doctor should fix that by default.
Thanks
=> default: tags should be a list

papis/fzf.py, papis/tui/__init__.py, papis/tui/app.py
I often have to browse multiple entrie so a shortcut is welcome.
Not tested on fzf.
=> Shortcut to browse_documents in pickers

.github/workflows/main.yml, .github/workflows/nix-flake.yml, .github/workflows/windows.yml, PACKAGING.md, papis/commands/serve.py, pyproject.toml, tools/create-docker-image.py, tools/test-all-py-versions-in-docker.sh
This adds Python 3.13 to `pyproject.toml` and in all the testing scripts.
=> Try Python 3.13 now that it's out

CHANGELOG.md, doc/source/default-settings.rst, papis/commands/doctor.py, papis/config.py, papis/defaults.py, papis/format.py, tests/test_doctor.py
This adds a `doctor-default-checks-extend` to `doctor-default-checks` (and same for other options) to allow users to extend instead of overwrite the various lists of keys and checks in there.
TODO:
cc @jghauser @apraga
=> Add extend config settings for doctor

papis/bibtex.py, papis/document.py, tests/test_bibtex.py
As shown in #885, some entries only have a single name author. This improves the handling of such entries by:
* Not doing `latex_to_unicode` on the whole author field. This removed the extra "{}" around an entry and confused "splitauthor" to think there are multiple names there.
* Adding a custom `author_list_to_author` for BibTeX so that we can handle author names in a smarter way. Now where there's a missing family or given name, it just uses `{name}` (with the curly braces, so that a roundtrip gives the same result).
Fixes #885.
=> Fix importing and exporting of institutional authors

doc/source/default-settings.rst, papis/bibtex.py, papis/defaults.py
Changes:
1. introduced a configuration option `ref-word-separator` (default "_")
2. I just think enforcing a word separator in refs is too opinionated ("-" looks better in the latex context)
I'm open to alternative ways of doing this, but I reckon other approaches would require more invasive revision of tests.
=> papis.config: add configuration ref-word-separator

papis/crossref.py
The `crossref.Downloader` was buggy because it didn't call `fetch` from `fetch_data`. This meant that running
```
papis add https://doi.org/10.1029/WR022i010p01404
```
wouldn't actually download any data because it was running the default `Downloader.fetch_data`.
=> crossref: implement fetch_data in terms of fetch

papis/arxiv.py, papis/bibtex.py, papis/hayagriva.py
This was fixed in #561 and got back in :(
cc @amine-aboufirass
=> Fix: masterthesis should be mastersthesis

papis/commands/bibtex.py, papis/defaults.py, papis/utils.py
This removes `ref` from `unique-document-keys` (and adds `eprint` instead). Depending on what `ref-format` the user sets, the `ref` may not be very unique at all. This can set off the duplicate warning incorrectly.
xref: https://github.com/papis/papis/discussions/935
=> Remove ref from unique-document-keys

.github/workflows/main.yml, CHANGELOG.md, tools/extract-changelog.py, tools/make-wheels.sh
This mostly uses the tutorial from here
https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
To work for actual releases, it needs:
* A `pypi` environment on Github: https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-deployments/managing-environments-for-deployment
* Adding the Github repo as a "trusted publisher" on PyPI: https://docs.pypi.org/trusted-publishers/adding-a-publisher/
I think we can add a step here to also make a Github release at the same time, but that would require a bit of scripting to get the changelog from `CHANGELOG.md`. Should be doable though.
@alejandrogallo @jghauser
=> Add PyPI release job

papis/commands/default.py
Small change to improve info when entering wrong commands.
Before:
```
❯ papis lsit
Command 'lsit' is unknown! Did you mean 'list'?
I suppose you meant: 'list'
[WARNING] commands.list: No documents retrieved
```
After
```
❯ papis lsit
Command 'lsit' is unknown!
I suppose you meant: 'list'
```
=> Better info wrong command

.github/workflows/windows.yml, tools/windows/get_version.py
This PR addresses the flakiness for the MSI version parsing. I think using this could do the trick.
The version for pre-releases would be in the format of MAJOR.MINOR.MICRO-LABEL.ID such as 0.14.0-rc.3 (like it was an hour ago), whereas for release versions or versions built during CI would be MAJOR.MINOR.MICRO.COUNT such as 0.14.0.0 for cut releases or 0.14.0.42 where 42 corresponds with the 42 in v0.14-**42**-dev000000 like in [this action run](https://github.com/papis/papis/actions/runs/11749836574/job/32736871128?pr=941#step:10:14).
Fixes #940.
Should I change the MSI artifact filenames too so that the filename coincides with the MSI version too?
cc @alexfikl
=> ci: parse version with python instead of awk

papis/config.py, papis/format.py
Changes:
1. minimally redefine `Jinja2Formatter` to expose the jinja environment as a class variable so it can be easily accessed by the user config and freely modified
2. this environment is used to create template instances directly instead of using the jinja2 Template class.
3. when a `Jinja2Formatter` is initialized the env is "shared" so all format strings should share the same env just as they did before (this claim needs more verification)
4. call configpy with `exec(fd.read(), globals())` instead of `exec(fd.read())`
The main change is (4). From reading https://docs.python.org/3/library/functions.html#exec this should be a fully back-compatible change, but I'm not sure.
This is necessary to allow any reasonably complicated custom function to be registered with the Jinja2Formatter …
=> papis.format: redefine Jinja2Formatter to enable easy template extension in config.py

papis/web/epubjs.py, papis/web/pdfjs.py
Following up on
https://github.com/papis/papis/issues/946#issuecomment-2473620039, I realigned
the code for `epubjs` and `pdfjs`, in case it's useful.
=> Align code structure of epubjs.py and pdfjs.py

papis/commands/add.py, papis/commands/update.py, papis/downloaders/__init__.py, papis/paths.py, papis/utils.py
This updates how `papis add` works when adding files:
* Files from importers are all included. Before, each importer asked for confirmation for each file.
* The `--open` flag opens files before they're added to the document for checking. Before, it would open them afterwards.
* The `--confirm` flag asks the user to add the file after it's been opened. Before, it would only ask for confirmation on downloaded files.
This way, when `--no-open` and `--no-confirm` is set, the files are just added without opening anything, as expected. Before, `collected_importer_data` would still open them up annoyingly.
xref: #956.
=> Confirm when adding files

papis/commands/add.py, papis/commands/addto.py, tests/commands/test_add.py
In some previous refactorings, the value passed on `papis add --file-name FILENAME` didn't get used when actually renaming the document files. The value from the config was always used instead, which is why this probably wasn't caught..
Fixes #963.
=> Use command-line filename when renaming

papis/tui/picker.py
This bug was introduced in a35643b927f5d9c1e69875ded148c386223eb325: basically the `redirect_stdout` context manager should have also wrapped the `tui.Picker(...)` constructor to work.
This refactors the code a bit and adds a few comments to document the purpose of the redirect.
Fixes #968.
=> Fix picker hang when piping output

.github/workflows/nix-flake.yml
The cache action does not seem to be available anymore according to https://determinate.systems/posts/magic-nix-cache-free-tier-eol/. I'm not sure if there's an alternative, but for now this just removes it..
cc @f0rki @jghauser
=> Remove magic-nix-cache-action from ci

papis/commands/cache.py, papis/database/whoosh.py
The `whoosh` backend needs a bit more initialization after calling `db.clear()`.
Fixes #975.
=> Ensure db is initialized on reset

README.rst, doc/source/index.rst
My papis-ask plugin is now in a reasonably ok state. I can index my whole library without errors and querying seems to work very well. @isaksamsten says [he would be archiving his repo](https://github.com/isaksamsten/papisqa/issues/1), so I'm replacing his papis-qa with my papis-ask in the README.
=> docs(readme): mention papis-ask instead of papis-qa

CHANGELOG.md, doc/source/default-settings.rst, papis/commands/export.py, papis/csl.py, papis/defaults.py, pyproject.toml, tests/test_csl.py
This adds some basic support for exporting citations using the CSL library [citeproc-py](https://github.com/citeproc-py/citeproc-py). It seems like development has picked up a bit over there, so it can't hurt to add it.
It still seems to have a few bugs to iron out, but hopefully they'll get to that by the time we make a new release as well. In particular the popular APA and MLA styles don't seem to be working :(
=> Add basic CSL exporting

doc/source/developer_reference.rst, papis/cli.py, papis/commands/add.py, papis/database/__init__.py, papis/database/base.py, papis/database/cache.py, papis/database/whoosh.py, papis/defaults.py, papis/format.py, papis/id.py, papis/testing.py, tests/commands/test_add.py, tests/commands/test_cache.py, tests/commands/test_rm.py, tests/database/test_database.py, tests/database/test_papis.py
I wanted to implement a backend based on sqlite and managed to amass a bunch of random cleanup stuff while looking through it. There's quite a few changes, but most of them are just moving things around.
Added some deprecations for the next next release (i.e. 0.16):
* Deprecated `papis.id.key_name()` in favour of a constant `papis.id.ID_KEY_NAME`.
* Deprecated `papis.id.has_id()` in favour of just using `ID_KEY_NAME in doc`.
* Deprecated `Database.get_lib`, `Database.get_dirs` and `Database.get_id_key` in favour of just accessing the members directly.
* Removed `Database.match` since it didn't seem to be used anywhere and was only implemented by the `papis` backend.
Some other changes:
* Made a bunch of methods "private" with a little underscore. I don't think these were ever meant to be …
=> Some general cleanup and refactoring for database backends

flake.nix, pyproject.toml
- **clean: Remove stale deps**
Testing reveals types-slugify is no longer needed
- **doc: Document optional features**
For this purpose, also split develop into style and test to make the components easier to document. The develop feature is left in place for ease of setup, other dev dependency components can be added to it as needed.
- **doc: Document deps for plugins using papis modules**
This way, packagers have a single source of truth to consult.
Closes: #984
=> Doc: Cleanup pyproject deps

flake.nix
I realised that after the recent cleanup, there's now an unused `types-python-slugify` in our flake. This PR removes it.
=> ci: remove unused types-python-slugify from flake

HACKING.md, flake.nix, pyproject.toml
As promised in https://github.com/papis/papis/pull/985#issuecomment-2759768177, here's an attempt to reduce the presence of `python-lsp-server` to merely an advertisement and a convenience feature in `flake.nix` (dropped from that PR since polishing this up was questionably-useful scope creep).
To recap the motivation for this: It isn't a dependency for the project, but merely a useful-to-have tool we recommend developers install. (This is unlike linters and test suites that allow us to maintain project standards -- in contrast, an LSP server is one way to configure a text editor for better Python support). In view of this, it doesn't make sense to advertise this as a component of the project (as is the implication by putting it in `pyproject.toml`).
Hopefully I've guessed the nix syntax …
=> Doc: Move LSP advertisement from pyproject.toml to docs

PACKAGING.md, papis/csl.py, pyproject.toml, tests/test_csl.py
This makes `citeproc-py` an optional dependency, since it causes some packaging issues.
cc @hseg
=> Make citeproc-py optional for the CSL exporter

papis/commands/doctor.py
This also cleans up abstracts that start with `Synopsis:` or `Summary:`. For an example: http://dx.doi.org/10.1002/fld.3923.
=> Add more handling for jats tags

papis/arxiv.py, papis/downloaders/__init__.py, papis/utils.py
When downloading metadata from importers using `get_matching_importer_by_name`, errors were only shown in debug mode. This made for some rather opaque issues when an importer would just fail to download something due to network issues.
This makes errors from `requests.exceptions.RequestException` louder so that they can be seen and debugged. Also added some more error messages for the arXiv importer, since that's where this started :grin:
xref: https://github.com/papis/papis/discussions/1031
=> Show HTTP errors from importers

papis/downloaders/usenix.py, papis/utils.py
For some reason cloudflare blocks only the access to the bibtex file, but not to the pdf or the html page itself. So while the downloader fails because it doesn't have access to the bibtex file, we can work around this by using the inline bibtex information that usenix provides on the html page they serve. This is not ideal, but seems to work for now.
=> Workaround to make the usenix downloader usable in face of cloudlflare

papis/paths.py, tests/test_paths.py
Slugify reserves the hyphen-minus character and always replaces it with the separator, even if the regex pattern excludes it https://github.com/un33k/python-slugify/issues/107. This fixes the problem by doing pre-processing if the hyphen-minus is included in `extra-chars`, as suggested in the issue. It does it for both the hyphen-minus (\u002d) and the hyphen (\u2010).
=> fix slugify always replacing hyphens

papis/commands/update.py
Adds a few sentences that `papis update --append` needs the `doctor-key-type-keys` configuration option to work for new keys.
cc @avonmoll Hope this helps!
cc @jghauser I couldn't find any other places where this could be mentioned, but let me know if anything else comes to mind :grin:
xref: #1063
=> Improve documentation for papis update --append
