papis/papis

ROADMAP.md

Spellchecked ROADMAP.md

---

papis/utils.py

fix use-cache=False option

---

papis/config.py
papis/crossref.py
papis/gui/rofi.py
papis/utils.py

Fix issue #21.
Also delete some extra whitespace and spellcheck config. I'm spellchecking files as I edit them so probably more of those to come

Fix rofi + housekeeping

---

papis/downloaders/base.py
papis/downloaders/ieee.py
papis/downloaders/utils.py

Download document and bibtex from IEEEXplore
papis add --from-url http://ieeexplore.ieee.org/document/7353481/

NEW: Add Downloader for IEEEXplore

---

papis/commands/add.py

Changed 'read and write' to just 'read'

---

papis/crossref.py

This was actually my fault! I had accidentally hard-coded the library I was using at the time. This should fix it!

Fixes #107

---

papis/crossref.py

Conference papers, such as [this one](https://ieeexplore.ieee.org/document/6758978) currently return 
`Can't locate metadata`. This allows them to be parsed by crossref.py and added to papis like journal papers.

Add support for conference papers to crossref parsing

---

examples/scripts/papis-tags

The papis tags script adds the ability to pick by tags from a
library. Closes #122

Added `papis-tags` script

---

papis/database/base.py

database: check if library folder exists

---

papis/commands/default.py
setup.cfg

more traditional. I am not sure which command outputs colors in order to test.

nc flag: convert to --color=always|auto|no

---

doc/source/configuration.rst
doc/source/database_structure.rst
doc/source/default-settings.rst
doc/source/faq.rst
doc/source/git.rst
doc/source/gui.rst
doc/source/importing.rst
doc/source/info_file.rst
doc/source/install.rst
doc/source/library_structure.rst
doc/source/quick_start.rst
doc/source/scripting.rst
doc/source/shell_completion.rst

Spell checking etc. as well as reformulating bumpy sentences.

Minor corrections for the documenation

---

doc/source/configuration.rst

changed typo in configuration.rst

---

papis/database/whoosh.py

Hi,
I noticed that papis crashed if whoosh-schema-fields was changed after initializing a library.  I've attempted to address this issue by checking if the user fields are the same as the database fields.
If they are not, the database is cleared and recreated.
Steps to reproduce the crash:
In the config file, set:
whoosh-schema-fields = ['<something not currentlly in whoosh-schema-fields']
Then, use papis add <pdf> --from-doi <doi>
This passes with no additional test failures.
Is this OK?
Jackson

whoosh: autoupdate on schema change

---

papis/api.py

Hopefully helping out a bit with #234 and learning about typing in python.
What's a good way to check that the additions are correct? For this, I just ran `mypy` over the file and checked that there are no errors specifically in it.

Add type information to api.py

---

papis/tui/widgets/list.py

I'm getting a hang that looks a lot like #240 (also on python 3.8) and this fixes it. 
This seems to be an issue in cpython according to [this bug report](https://bugs.python.org/issue38744).

OptionsList: create the pool on demand instead

---

papis/commands/default.py

Hi,
papis was  acting a bit slow for me the other day, so I added a command to debug that.  Command use is:
`papis --profile <filename to dump into> command`
It doesn't work very well with things like `open "*"` where the picker can take a lot of time but  is good for working out why the backend is being so slow.
OK to go in?
Jackson

Add papis --profile to enable debugging when papis is slow

---

papis/config.py

Using `master` and noticed it's writing this file for no reason (?).

Remove writing test.conf

---

LICENSE
README.rst

https://github.com/papis/papis/issues/286
I added the license to the end of README and changed the LICENSE file to the complete GPLv3 text.

GPL-3.0-or-later

---

papis/isbn.py
setup.py
tests/test_isbn.py

This will allow doing `papis add --from isbn 'I-S-B-N' file`.

Add Importer for ISBN

---

papis/crossref.py

When running 
```
papis add --from doi '10.1007/s00607-002-1450-4'
```
the importer would get a `doc_url` of http://link.springer.com/article/10.1007/s00607-002-1450-4/fulltext.html, which would get redirected to the default paper page because of lack of access, and then download that as an html document.
I'm not sure disallowing redirects is the best way to handle that, since there are legitimate uses for them. What do you think?

Stricter file download checks in crossref

---

papis/__init__.py
papis/arxiv.py
papis/bibtex.py
papis/commands/add.py
papis/commands/bibtex.py
papis/commands/default.py
papis/commands/explore.py
papis/commands/list.py
papis/commands/merge.py
papis/commands/mv.py
papis/commands/update.py
papis/config.py
papis/crossref.py
papis/docmatcher.py
papis/downloaders/__init__.py
papis/downloaders/acs.py
papis/downloaders/base.py
papis/downloaders/thesesfr.py
papis/importer.py
papis/tui/__init__.py
papis/tui/utils.py
papis/tui/widgets/diff.py
tests/test_document.py
tests/tui/widgets/test_options_list.py
tools/ci-install.sh
tools/ci-run-tests.sh

At least locally this seems to make all the tests pass (fingers crossed).

Small fixes to various tests

---

doc/source/configuration.rst
doc/source/default-settings.rst
doc/source/git.rst
papis/base.py
papis/bibtex.py
papis/commands/add.py
papis/commands/bibtex.py
papis/commands/browse.py
papis/commands/default.py
papis/commands/export.py
papis/database/base.py
papis/database/whoosh.py
papis/docmatcher.py
papis/downloaders/annualreviews.py
papis/format.py
papis/isbn.py
papis/isbnplus.py
papis/tui/utils.py
papis/tui/widgets/diff.py
papis/utils.py

I was playing with [codespell](https://github.com/codespell-project/codespell) and wanted to use it on a larger project. These are the typos it found.

Fix some spelling mistakes using codespell

---

papis/yaml.py

See also https://stackoverflow.com/a/50685946.

Use CSafeLoader for yaml for faster loading

---

doc/source/install.rst

Update links to papis repository in install docs

---

papis/utils.py

Disable multiprocessing on darwin systems

---

papis/commands/serve.py

Add javascript support to dynamically filter the table result

DataTables

---

doc/source/api.rst
doc/source/conf.py
doc/source/configuration.rst
doc/source/database_structure.rst
doc/source/default-settings.rst
doc/source/document.rst
doc/source/editors.rst
doc/source/faq.rst
doc/source/git.rst
doc/source/gui.rst
doc/source/hooks.rst
doc/source/importing.rst
doc/source/index.rst
doc/source/info_file.rst
doc/source/install.rst
doc/source/quick_start.rst
doc/source/scripting.rst
doc/source/shell_completion.rst
doc/sphinx.mk
papis/commands/bibtex.py
papis/commands/explore.py
papis/database/cache.py
papis/database/whoosh.py
papis/plugin.py
papis/utils.py

Running with
```
make html SPHINXOPTS="-W --keep-going -n"
```
showed quite a few errors, which this should fix.

Fix doc generation

---

.readthedocs.yml

Manage to miss a typo in the path! Hopefully this works

Fix rtd conf.py path

---

README.rst
doc/vhs/add.tape
doc/vhs/bibtex_export.tape
doc/vhs/edit.tape
doc/vhs/first_glance.tape

This is the new version of the README. It's still WiP and I'm happy about any feedback. Also happy to explain why I dropped certain things and added others if there are any questions.
Note that the gifs are a biiit speedy, which I still hope to fix. I'm making them with [vhs](https://github.com/charmbracelet/vhs) and apparently I'm dropping too many frames when generating them, leading to everything being sped up. They're also currently hosted on my nextcloud and probably won't load super fast (@alejandrogallo , can you give me write access to our github pages, so I can upload them there just as the old gifs were)?

WIP: Update readme

---

papis/base.py
papis/bibtex.py
papis/commands/add.py
papis/commands/addto.py
papis/commands/default.py
papis/config.py
papis/crossref.py
papis/dissemin.py
papis/document.py
papis/isbnplus.py
papis/utils.py

The extra method call is not necessary (probably not a big performance win, but reads nicer!)

Do no use dict.keys() if not necessary

---

papis/api.py
papis/arxiv.py
papis/bibtex.py
papis/commands/add.py
papis/commands/export.py
papis/commands/list.py
papis/config.py
papis/crossref.py
papis/database/base.py
papis/database/cache.py
papis/database/whoosh.py
papis/docmatcher.py
papis/document.py
papis/downloaders/__init__.py
papis/format.py
papis/git.py
papis/importer.py
papis/isbn.py
papis/tui/utils.py
papis/tui/widgets/command_line_prompt.py
papis/tui/widgets/diff.py
papis/utils.py
papis/yaml.py

Type annotations do a much better job at documenting these.

Remove all :type: directives

---

papis/arxiv.py
papis/bibtex.py
papis/commands/doctor.py
papis/commands/serve.py
papis/crossref.py
papis/downloaders/hal.py
papis/isbn.py
papis/pubmed.py
papis/web/paths.py

Cleans up the strings that show up when calling
```
papis add --list-importers
```

Minor clean up in importer docs

---

tests/test_isbn.py
tests/test_pubmed.py

These keep failing every once in a while in an annoying way :cry:

xfail ISBN and PubMed tests that sometimes timeout

---

papis/arxiv.py

I sometimes have pdfs from arXiv that are conveniently named `<arxivid>.pdf` so its easier to do a `papis add --from arxiv '<arxivid>' <arxivid>.pdf` and not fill out the whole url.
This adds support to the `Importer` to first check if it's an id.

arxiv: support both urls and arxivids in importer

---

papis/arxiv.py
papis/bibtex.py
papis/commands/add.py
papis/config.py
papis/crossref.py
papis/database/cache.py
papis/database/whoosh.py
papis/downloaders/__init__.py
papis/exceptions.py
papis/pubmed.py
papis/tui/app.py
papis/tui/widgets/__init__.py
papis/tui/widgets/command_line_prompt.py
papis/tui/widgets/list.py
papis/yaml.py
tests/test_importer.py

There were a couple of python2 versions around. Hopefully got them all!

Use python3 style super() everywhere

---

papis/cli.py
papis/commands/addto.py
papis/commands/bibtex.py
papis/commands/browse.py
papis/commands/citations.py
papis/commands/doctor.py
papis/commands/edit.py
papis/commands/explore.py
papis/commands/export.py
papis/commands/list.py
papis/commands/merge.py
papis/commands/mv.py
papis/commands/open.py
papis/commands/rename.py
papis/commands/rm.py
papis/commands/update.py

In addition, I changed the `query_option` declaration name since it was
not an option but an argument, and I corrected this in all commands.
This should be quite useful for people writing papers or documents often.

Make papis bibtex able to add documents from a file with a list of references

---

doc/source/api.rst
doc/source/conf.py
papis/api.py

Was looking at the functions in `api.py` and did some small drive-by formatting and phrasing changes to the docs.
The biggest change is probably adding proper wrappers around `pick` and `pick_doc` with full docs.

Update user-facing API docs

---

papis/utils.py

Tell `subprocess.Popen` to disown the process. Fixes #475.

---

papis/commands/doctor.py
tests/test_doctor.py

Doctor: fix config option names in docs

---

papis/commands/add.py

This improves the handling when a duplicate document is found like suggested in #509:
* The `'Duplicate Warning...'` log message is moved after the dump of the existing document, so that it sits right above the `'Add? Y/n'` prompt.
* If the user answered yes and the folder already exists, it tries `folder-a`, `folder-b`, etc. until a new one is found and uses that for the new (duplicate) document.
@jghauser What do you think of this?
Fixes #509.

commands.add: handle duplicate doc with existing folder

---

papis/commands/add.py
papis/commands/bibtex.py
papis/commands/browse.py
papis/commands/default.py
papis/commands/doctor.py
papis/commands/export.py
papis/downloaders/__init__.py
papis/tui/utils.py

According to their docs
https://click.palletsprojects.com/en/8.1.x/utils/#printing-to-stdout
this is nicer because it's more uniform across platforms and supports unicode in Windows console.

Use click.echo instead of print

---

papis/utils.py

This cleans up and updates the documentation for all the functions in `papis.utils`.
It also contains some other drive-by changes:
* `clean_document_name`: adds an `is_path` keyword to disable the use of `os.path.basename`, since this may be useful in some places.
* `locate_document_in_lib`: avoid some repeated key accesses.
* use `Iterable` instead of `List` for input annotations in functions. My general rule-of-thumb is that the inputs should be as generic as possible, and the outputs should be as specific as possible.

utils: improve docs

---

papis/citations.py
papis/commands/bibtex.py
papis/commands/list.py
papis/commands/rm.py
papis/database/base.py
papis/document.py
papis/web/citations.py
papis/web/document.py

This does
* some doc updates to `papis.document`.
* clean up `papis.document.sort` a bit by introducing an `enum` for the priorities.

document: update and add docs

---

papis/yaml.py
tests/commands/test_export.py

Some small cleanup in the docs and annotations for `papis.yaml`.

yaml: improve docs

---

doc/source/default-settings.rst
doc/source/gui.rst
doc/source/importing.rst
doc/source/index.rst
doc/source/info_file.rst
doc/source/install.rst
doc/source/quick_start.rst
doc/source/scihub.rst
doc/source/scripting.rst
papis/arxiv.py
papis/bibtex.py
papis/commands/__init__.py
papis/commands/explore.py
papis/database/whoosh.py
papis/downloaders/acs.py
papis/downloaders/annualreviews.py
papis/downloaders/get.py
papis/downloaders/ieee.py
papis/downloaders/iopscience.py
papis/downloaders/scitationaip.py
papis/downloaders/springer.py
papis/downloaders/tandfonline.py
papis/downloaders/thesesfr.py
tests/commands/test_add.py
tests/test_arxiv.py

Also went through the code to use HTTPS instead of HTTP (hopefully everywhere).

Fix some broken links in the docs

---

doc/source/conf.py
papis/arxiv.py
papis/commands/add.py
papis/commands/edit.py
papis/commands/external.py
papis/commands/rm.py
papis/commands/serve.py
papis/commands/update.py
papis/docmatcher.py
papis/downloaders/__init__.py
papis/fzf.py
papis/notes.py
papis/tui/utils.py
papis/tui/widgets/diff.py
papis/utils.py
setup.py
tests/commands/test_edit.py
tests/test_isbn.py
tests/testlib.py
tools/create-docker-image.py

Ran [pyupgrade](https://github.com/asottile/pyupgrade) fixes over the code except the one that transforms `str.format` into f-strings.

Run pyupgrade fixes

---

doc/source/conf.py
doc/source/default-settings.rst
doc/source/developer_reference.rst
papis/bibtex.py
papis/downloaders/__init__.py

This updates the docs for `papis.bibtex` and adds them to the Developer API section in the docs to make sure they stay vaguely updated.

Update papis.bibtex docs

---

papis/crossref.py
papis/format.py

This adds / fixes some logging messages.

Fix confusing message when doi is not found

---

doc/source/configuration.rst
papis/arxiv.py
papis/bibtex.py
papis/commands/doctor.py
papis/commands/explore.py
papis/commands/export.py
papis/crossref.py
papis/dblp.py
papis/dissemin.py
papis/isbn.py
papis/json.py
papis/yaml.py

This fixes some more formatting issues, mostly around `papis explore`.

Fix commands docs (cont.)

---

papis/document.py

@alejandrogallo Hopefully this fixes your issue! There's probably more lurking around though :worried:

document: fix format default in describe

---

papis/config.py

Remove incorrect warning in register_default_settings

---

papis/cli.py
papis/commands/addto.py
papis/commands/browse.py
papis/commands/cache.py
papis/commands/citations.py
papis/commands/doctor.py
papis/commands/edit.py
papis/commands/explore.py
papis/commands/export.py
papis/commands/list.py
papis/commands/mv.py
papis/commands/open.py
papis/commands/rename.py
papis/commands/rm.py
papis/commands/run.py
papis/commands/update.py

doc_folder_option handles multiple folders

---

.github/workflows/nix-flake.yml
tests/test_config.py

@f0rki Cherry-picked from #612. This tries to preserve authorship and hopefully doesn't mess it up too much.

ci: add workflow for testing nix flake

---

Dockerfile

Forgot to change this in #647 :(

docker: fix renamed script

---

papis/commands/doctor.py
tests/test_doctor.py

@f0rki Cherrypicked from #598.

commands.doctor: add fixer for key-type check

---

CHANGELOG.md

Added some features and bug fixes for the next release.

Start CHANGELOG for version 0.14

---

papis/commands/doctor.py

@alejandrogallo This adds an `--all-checks` flag like you suggested in https://github.com/papis/papis/pull/663#issuecomment-1712912888

commands.doctor: add an --all-checks flag to run everything

---

CHANGELOG.md
papis/web/docview.py
papis/web/epubjs.py

I'm very happy about this, now I can read some books from the webapp
from my tablet!
One thing that remains a todo is implement a way to have bookmarks and save them in the info file.

Add epub support for the webapp

---

doc/source/commands/init.rst
papis/commands/init.py

This also slightly improves the docs so that they are more in line with the other commands.

docs: add papis init to the docs

---

papis/commands/doctor.py
papis/defaults.py
papis/document.py
tests/test_doctor.py

@f0rki Cherrypicked from #598.

commands.doctor: add fixers for keys-exist

---

examples/scripts/papis-tags
papis/commands/add.py

Had some strange behaviour with my settings not taking effect, and I think the reason is that this should be getting a boolean option.

fix getting add-download-files

---

.github/workflows/main.yml
papis/dissemin.py
papis/tui/app.py
setup.py

Added on the CI to see if everything works. Python 3.12 just came out two days ago, so probably not all libraries are updated..

Advertise support for python 3.12

---

papis/commands/config.py

Can be useful for debugging and letting users know what the config folders are.

commands.config: print known config paths

---

doc/source/conf.py

This links the docs back to Github when clicking the `[source]` buttons (see [here](https://papis.readthedocs.io/en/latest/api.html)). Currently it shows something like this:
https://papis.readthedocs.io/en/latest/_modules/papis/api.html#get_lib_name
and with this change it would redirect to
https://github.com/papis/papis/blob/main/papis/api.py#L36-L46
@alejandrogallo @jghauser What do you think?

docs: use linkcode instead of viewcode

---

papis/arxiv.py

Very small fix to remove some deprecation warnings.

arxiv: fix arxiv.py 2.0 deprecations

---

papis/commands/add.py

This moves around the code in `get_file_name` to ensure that a non-empty file name is generated. This can happen if the document is missing all the fields for the `add-file-name` option.
* Before: `papis.format.format(add_file_name_format)` would return something like `"--"`, which would be cleaned by `papis.utils.clean_document_name` before returning to an empty string `""`.
* After: the string is cleaned right after the `format` so we check if it's empty and reuse the `original_filepath`.

commands.add: retain original file path if format fails

---

doc/source/git.rst

Mostly update phrasing a bit and remove some out of date command arguments.

docs: update git docs a bit

---

.github/workflows/codeql.yml
.github/workflows/main.yml
.github/workflows/nix-flake.yml

Updates the versions for all the GitHub actions we use.

ci: update actions

---

papis/tui/app.py

This gets around `prompt_toolkit` not allowing multiple event loops by spawning a thread to run the open command in case it has multiple files.
@jghauser Can you try and see if this fixes the bug for you? I just hit it too and was motivated to fix it :grin:
Fixes #315.

picker: fix opening multiple files

---

papis/commands/add.py

To complement `--link` and the default `--copy` for the adventurous. The move is only performed only at the end, so that data doesn't just disappear on a weird failure.

commands.add: add a --move flag

---

papis/bibtex.py
tests/test_bibtex.py

This uses the writer from bibtexparser to remove some of our own BibTeX parsing and skips escaping URLs.
Fixes #738.

bibtex: use bibtexparser.bwriter and skip escaping URLs

---

.github/workflows/codeql.yml
.github/workflows/main.yml
.github/workflows/nix-flake.yml
Makefile
flake.lock
flake.nix

Sorry for the slow response time. Updated the nix flake and the CI to conform to nix/CI best practices (i.e., maximum caching).
Fixes #733

Ci flake update

---

Dockerfile
release.Dockerfile

@jghauser Can you check if this works? I apparently managed to break it in e46fc5888ad953ad890d7eee9357e697309f742f because I don't understand how Docker files work. Sorry about that! :cry:

docker: fix image

---

tests/database/test_whoosh.py

test_whoosh:test_cache_path: Check whoosh installed

---

doc/source/default-settings.rst
papis/format.py
papis/sphinx_ext.py

Fixed some small issues from #709 and #752.

docs: fix format docs

---

tests/test_zenodo.py

tests: run zenodo tests conditionally on markdownify

---

papis/zenodo.py
setup.cfg

fix: add markdownify to mypy ignores

---

.readthedocs.yml

Update optional dependencies for building the docs.
xref: #607.

docs: fix readthedocs build

---

papis/commands/merge.py

I'm going through the TODOs scattered around the code, so I can learn more about the papis code.
I found a documentation TODO and I think i managed to resolve it.
It's my first doc here so let me know if it's alright. I checked it in browser and it doesn't look bad.

docs(merge): resolve TODO and add examples

---

HACKING.md
Makefile

Mostly changed some lists into enumerations and rephrased a few sentences.

docs: update hacking docs a bit

---

CHANGELOG.md
doc/source/default-settings.rst
tests/tui/test_app.py

I forgot to add the config documentation for #820. I added the minor improvements to the changelog too, so you don't have to do it.

Add docs and a test line for #820

---

papis/__main__.py

This allows running `python -m papis ...`.

feat: add a __main__.py entry point

---

README.rst

readme: update papis-zotero maintainer

---

papis/format.py

New mypy is out!
https://github.com/python/mypy/blob/master/CHANGELOG.md

fix: types for mypy 1.10.0

---

papis/json.py

This should make the export a bit more readable.

json: sort and indent results on export

---

papis/fzf.py

This uses the new `become` action that handles calling and returning the output of external commands in fzf correctly.
Fixes #869
cc: @xmalbertox @tuurep

fzf: switch from execute to become calls

---

papis/zenodo.py

New `markdownify` 0.13 also escapes `[` and `#`, which we do not want. This selectively disables that escaping.

Fix Zenodo importer

---

papis/commands/explore.py

commands.explore: update doc commands

---

doc/source/developer_reference.rst
doc/source/hooks.rst
papis/commands/add.py
papis/commands/edit.py
papis/hooks.py

This adds a hook that gets called after all the editing in `papis add`. It should allow for some final touch-ups.

Add a on_add_done hook

---

papis/commands/serve.py

This ports away from the deprecated `cgi` module in the standard library that will be removed in Python 3.13 (coming out this fall). The `read_urlencoded` function is mostly copied from the standard library and the rest of the code is a thin wrapper around that.
https://docs.python.org/3.13/whatsnew/3.13.html#pep-594-dead-batteries-and-other-module-removals
Note that this is just a stopgap until `papis serve` gets ported to `flask` or something more capable.
@alejandrogallo I've tested this a bit and it works when adding new keys to the document, updating the `info.yaml` file, adding to `notes.md`. I'm not sure that any more advanced usage works, since I don't use `papis serve`, so any additional testing is very appreciated!

commands.serve: port away from cgi.FieldStorage

---

README.rst

Follow-up on #915. I don't know how you recorded the GIF (#825) and I don't have the same colorscheme :)

Update README with picker shortcut and bibtex import.

---

PACKAGING.md
tests/commands/test_add.py
tests/commands/test_git.py
tests/commands/test_rm.py

test: add pytest marker for git executable

---

papis/bibtex.py

bibtex: add error on incorrect author

---

README.rst

Add bibiman to readme

---

papis/commands/doctor.py
papis/commands/tag.py

Fix the typos discussed in issue #965

fix check -> checks

---

.codespell-ignore
.github/workflows/main.yml
.github/workflows/nix-flake.yml
.github/workflows/windows.yml
CHANGELOG.md
HACKING.md
Makefile
doc/source/index.rst
papis/bibtex.py
papis/crossref.py
papis/dblp.py
papis/defaults.py
papis/downloaders/__init__.py
papis/downloaders/citeseerx.py
papis/downloaders/get.py
papis/downloaders/hal.py
papis/pick.py
papis/strings.py
pyproject.toml
tests/commands/test_add.py
tests/downloaders/test_citeseerx.py
tests/downloaders/test_thesesfr.py

This adds [typos](https://github.com/crate-ci/typos) to the CI to check or spelling errors.

Add typos for spellchecking

---

PACKAGING.md

This adds a small description for each optional dependency we have, so people can decide if they want it.
cc @hseg

Document optional dependencies in PACKAGING

---

papis/commands/serve.py
papis/config.py
papis/crossref.py
papis/format.py
papis/plugin.py

This seems to be a new warning added in the newly released flake8: https://github.com/PyCQA/pyflakes/pull/825.

Fix unused global warnings from new flake8 7.2.0

---

papis/commands/explore.py

The `papis explore` command pretty much imported everything else. This makes most of the imports lazy.
The main motivation was just reduce the chance of cyclic imports and slightly improve the import speed (`hyperfine` reports 5ms).

feat(explore): make more imports lazy

---

papis/commands/doctor.py

fix: small indentation error in docs
